[package]
name = "rorolala-daemon"
version.workspace = true
edition.workspace = true

[dependencies]
rorolala-auth.workspace = true
rorolala-errors.workspace = true
rorolala-protocol.workspace = true
rorolala-storage.workspace = true
rorolala-utils-cli-theme.workspace = true
rorolala-utils-configure.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-lazyffi.workspace = true
rorolala-utils-location.workspace = true
rorolala-vault.workspace = true
rorolala-workspace.workspace = true

tokio = { workspace = true, features = ["io-util"] }
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
syn.workspace = true
just_template.workspace = true

[dev-dependencies]
ed25519-dalek = { workspace = true, features = ["pem", "pkcs8"] }
