// Generated by `rorolala-dev-icons` from `app/desktop/icons.toml`.
//
// Do not edit: what this holds is what the manifest says, and a change made here is a change made
// nowhere — the next `./run.sh icons` would take it away again.

namespace FileSystemPlugin;

/// <summary>The pictures this plugin contributes, and the key each is handed over under.</summary>
internal static partial class Icons
{
    /// <summary>The key the `visibility` picture is held under.</summary>
    public const string Visibility = "rorolala_file_system.visibility";

    /// <summary>The key the `visibility_off` picture is held under.</summary>
    public const string VisibilityOff = "rorolala_file_system.visibility_off";

    /// <summary>The key the `link` picture is held under.</summary>
    public const string Link = "rorolala_file_system.link";

    /// <summary>The key the `link_off` picture is held under.</summary>
    public const string LinkOff = "rorolala_file_system.link_off";

    /// <summary>The key the `arrow_back` picture is held under.</summary>
    public const string ArrowBack = "rorolala_file_system.arrow_back";

    /// <summary>The key the `arrow_forward` picture is held under.</summary>
    public const string ArrowForward = "rorolala_file_system.arrow_forward";

    /// <summary>The key the `arrow_upward` picture is held under.</summary>
    public const string ArrowUpward = "rorolala_file_system.arrow_upward";

    /// <summary>The key the `refresh` picture is held under.</summary>
    public const string Refresh = "rorolala_file_system.refresh";

    /// <summary>The key the `launch` picture is held under.</summary>
    public const string Launch = "rorolala_file_system.launch";

    /// <summary>The key the `file_copy` picture is held under.</summary>
    public const string FileCopy = "rorolala_file_system.file_copy";

    /// <summary>The key the `content_cut` picture is held under.</summary>
    public const string ContentCut = "rorolala_file_system.content_cut";

    /// <summary>The key the `content_paste` picture is held under.</summary>
    public const string ContentPaste = "rorolala_file_system.content_paste";

    /// <summary>The key the `delete` picture is held under.</summary>
    public const string Delete = "rorolala_file_system.delete";

    /// <summary>The key the `local_offer` picture is held under.</summary>
    public const string LocalOffer = "rorolala_file_system.local_offer";

    /// <summary>The key the `create_new_folder` picture is held under.</summary>
    public const string CreateNewFolder = "rorolala_file_system.create_new_folder";

    /// <summary>Every picture, by the key it is held under and its name in the set.</summary>
    public static readonly (string Key, string Name)[] Pictures =
    [
        (Visibility, "visibility"),
        (VisibilityOff, "visibility_off"),
        (Link, "link"),
        (LinkOff, "link_off"),
        (ArrowBack, "arrow_back"),
        (ArrowForward, "arrow_forward"),
        (ArrowUpward, "arrow_upward"),
        (Refresh, "refresh"),
        (Launch, "launch"),
        (FileCopy, "file_copy"),
        (ContentCut, "content_cut"),
        (ContentPaste, "content_paste"),
        (Delete, "delete"),
        (LocalOffer, "local_offer"),
        (CreateNewFolder, "create_new_folder"),
    ];
}
