[package]
name = "rorolala-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blake3.workspace = true
lz4.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-location.workspace = true
serde.workspace = true
size.workspace = true
tokio = { workspace = true, features = ["io-util"] }
toml.workspace = true
zstd.workspace = true
