[workspace]
resolver = "3"
members = [
    "app/cli/rola",
    "app/cli/rola-daemon",
    "app/cli/setups",
    "app/ffi",
    "dev/bindgen",
    "modules/auth",
    "modules/daemon",
    "modules/protocol",
    "modules/vault",
    "modules/workspace",
    "utils/cli-theme",
    "utils/configure",
    "utils/configure-macros",
    "utils/constants",
    "utils/lazyffi",
    "utils/lazyffi-core",
    "utils/lazyffi-macros",
    "utils/location"
]

[workspace.package]
license = "MIT OR Apache-2.0"
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
# Members
librorolala = { path = "." }
rola = { path = "app/cli/rola" }
rola-daemon = { path = "app/cli/rola-daemon" }
rorolala-auth = { path = "modules/auth" }
rorolala-cli-setups = { path = "app/cli/setups" }
rorolala-daemon = { path = "modules/daemon" }
rorolala-dev-bindgen = { path = "dev/bindgen" }
rorolala-ffi = { path = "app/ffi" }
rorolala-protocol = { path = "modules/protocol" }
rorolala-utils-cli-theme = { path = "utils/cli-theme" }
rorolala-utils-configure = { path = "utils/configure" }
rorolala-utils-configure-macros = { path = "utils/configure-macros" }
rorolala-utils-constants = { path = "utils/constants" }
rorolala-utils-lazyffi = { path = "utils/lazyffi" }
rorolala-utils-lazyffi-core = { path = "utils/lazyffi-core" }
rorolala-utils-lazyffi-macros = { path = "utils/lazyffi-macros" }
rorolala-utils-location = { path = "utils/location" }
rorolala-vault = { path = "modules/vault" }
rorolala-workspace = { path = "modules/workspace" }

# CLI Framework
mingling = { version = "0.5.2", features = ["picker", "comp", "pathf"] }

# Serialization
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
serde_yaml = "0.9.34"
toml = "0.8.23"

# CLI Rendering
bat = { version = "0.26.1", default-features = false, features = ["regex-fancy"] }
colored = "3.1.1"
console = "0.16.6"
prettytable-rs = { version = "0.10.0", default-features = false }
unicode-width = "0.2.2"

# Internationalization
rust-i18n = "4.2.2"

# Filesystem
dirs = "6.0.0"

# Proc macro
annotate-snippets = "0.12.16"
just_fmt = "0.2.1"
proc-macro2 = { version = "1.0.107", features = ["span-locations"] }
quote = "1.0.47"
syn = { version = "3.0.5", features = ["full"] }

# Async Runtime
tokio = { version = "1.53.1", features = [
    "fs",
    "macros",
    "net",
    "rt",
    "rt-multi-thread",
    "signal",
    "sync",
] }

[package]
name = "librorolala"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
rorolala-auth.workspace = true
rorolala-daemon.workspace = true
rorolala-protocol.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-lazyffi.workspace = true
rorolala-utils-location.workspace = true
rorolala-vault.workspace = true
rorolala-workspace.workspace = true

[build-dependencies]
rorolala-dev-bindgen.workspace = true
serde_json.workspace = true
