// Generated by `build.rs` from `src/exit_codes.rs`.
// Do not edit: change the key an exit code carries in the source, or `tmpl/explain.tmpl`,
// and this follows.
//
// Every exit code the program states, with the `i18n/exit_codes.yml` key it is written
// under. `build.rs` reads the keys from the source, so a code and its words cannot
// disagree about which of them is which.

use rust_i18n::t;

/// Every exit code the program states, in number order.
///
/// The codes are in number order, which is not the order they are written in: the source
/// groups them by what they are about, and a reader who has a number wants it by number.
#[rustfmt::skip]
pub const CODES: &[i32] = &[
    2,
    3,
    11,
    12,
    13,
    21,
    22,
    23,
    41,
    42,
    43,
    44,
    45,
    46,
    47,
    48,
    49,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    63,
    64,
    65,
    66,
    67,
    71,
    72,
    73,
    81,
    82,
    83,
    84,
    85,
    86,
    87,
    88,
    89,
    90,
    91,
    92,
    93,
];

/// Whether the program states the exit code `code`.
///
/// This is the question [`explain_ec`] answers with an empty string, asked on its own: a
/// caller that has to tell "no such code" from "a code with nothing said about it" asks
/// this rather than reading the string, since a code the program states always has a key
/// with something under it.
#[must_use]
pub fn has_ec(code: i32) -> bool {
    CODES.contains(&code)
}

/// What the exit code `code` means, in the words `i18n/exit_codes.yml` holds for the key it
/// carries, spoken in the run's language.
///
/// An empty string when the program states no such code; ask [`has_ec`] to tell that apart
/// from a code whose words are still to be written.
#[must_use]
pub fn explain_ec(code: i32) -> String {
    match code {
        2 => t!("exit_codes.help").to_string(),
        3 => t!("exit_codes.cancelled").to_string(),
        11 => t!("exit_codes.already_exist").to_string(),
        12 => t!("exit_codes.not_exist").to_string(),
        13 => t!("exit_codes.unknown_command").to_string(),
        21 => t!("exit_codes.creation_workspace").to_string(),
        22 => t!("exit_codes.creation_vault").to_string(),
        23 => t!("exit_codes.creation_argument").to_string(),
        41 => t!("exit_codes.tool_keygen_no_openssl").to_string(),
        42 => t!("exit_codes.tool_keygen_failed").to_string(),
        43 => t!("exit_codes.tool_keygen_path_not_exist").to_string(),
        44 => t!("exit_codes.tool_keygen_no_key_dir").to_string(),
        45 => t!("exit_codes.tool_keygen_install_failed").to_string(),
        46 => t!("exit_codes.tool_write_file_argument").to_string(),
        47 => t!("exit_codes.tool_write_file_no_storage").to_string(),
        48 => t!("exit_codes.tool_write_file_not_a_file").to_string(),
        49 => t!("exit_codes.tool_write_file_failed").to_string(),
        51 => t!("exit_codes.config_unreadable").to_string(),
        52 => t!("exit_codes.vault_argument").to_string(),
        53 => t!("exit_codes.vault_not_bound").to_string(),
        54 => t!("exit_codes.tool_extract_file_argument").to_string(),
        55 => t!("exit_codes.tool_extract_file_no_storage").to_string(),
        56 => t!("exit_codes.tool_extract_file_bad_hash").to_string(),
        57 => t!("exit_codes.tool_extract_file_exists").to_string(),
        58 => t!("exit_codes.tool_extract_file_failed").to_string(),
        59 => t!("exit_codes.pack_no_storage").to_string(),
        60 => t!("exit_codes.pack_failed").to_string(),
        61 => t!("exit_codes.account_not_found").to_string(),
        62 => t!("exit_codes.account_no_dir").to_string(),
        63 => t!("exit_codes.account_not_bound").to_string(),
        64 => t!("exit_codes.tool_ls_storaged_no_storage").to_string(),
        65 => t!("exit_codes.tool_ls_storaged_failed").to_string(),
        66 => t!("exit_codes.tool_ls_manifests_no_storage").to_string(),
        67 => t!("exit_codes.tool_ls_manifests_failed").to_string(),
        71 => t!("exit_codes.should_in_workspace").to_string(),
        72 => t!("exit_codes.should_in_vault").to_string(),
        73 => t!("exit_codes.no_remote_vault").to_string(),
        81 => t!("exit_codes.action_no_channel").to_string(),
        82 => t!("exit_codes.action_missing_value").to_string(),
        83 => t!("exit_codes.action_value_too_large").to_string(),
        84 => t!("exit_codes.action_io").to_string(),
        85 => t!("exit_codes.action_codec").to_string(),
        86 => t!("exit_codes.action_unknown").to_string(),
        87 => t!("exit_codes.action_json").to_string(),
        88 => t!("exit_codes.action_addr").to_string(),
        89 => t!("exit_codes.action_auth").to_string(),
        90 => t!("exit_codes.action_missing_object").to_string(),
        91 => t!("exit_codes.explain_unknown").to_string(),
        92 => t!("exit_codes.explain_no_lastec").to_string(),
        93 => t!("exit_codes.action_store").to_string(),
        _ => String::new(),
    }
}
