//! Generates the C header for Rorolala's `#[lazyffi]` surface.
//!
//! A generic generator cannot render `#[lazyffi]` output: the generated
//! signatures are written in terms of associated types (`<T as InputType>::From`),
//! which it has no way to resolve. This generator knows the `#[lazyffi]` rules
//! instead, so it works straight from the sources — no macro expansion, and no
//! nightly toolchain.
//!
//! The rules themselves come from `rorolala-utils-lazyffi-core`, the same crate
//! the attribute macro uses, so the two cannot drift apart.
//!
//! A type the generator cannot map to C is reported as an error pointing at the
//! offending line, never skipped: an incomplete header is worse than no header.
//!
//! # Tradeoff: `export` is parsed twice
//!
//! The `export = <Name>` override is parsed here *and* in
//! `rorolala-utils-lazyffi-macros`, and that duplication is deliberate.
//!
//! The two never see the same input. An attribute macro receives its item with the
//! `#[lazyffi]` attribute **already stripped**, so the macro can only read `export`
//! from the attribute's own argument tokens; this generator reads the sources, so
//! it sees `#[lazyffi(export = ...)]` in place and parses it out of the item's
//! attributes. There is no shared shape to factor out — only the *defaults* are,
//! and those do live in `rorolala-utils-lazyffi-core`.
//!
//! What must not drift is therefore the naming rule (`ffi_<snake>` / `FFI<Pascal>`)
//! and the built-in repr table, not this parser. If you add a second attribute
//! argument, you have to teach both parsers about it.

#![doc = include_str!("../README.md")]
#![deny(missing_docs)]
#![deny(warnings)]
#![deny(rust_2018_idioms)]
#![deny(clippy::pedantic)]
#![deny(clippy::nursery)]

use std::collections::BTreeMap;
use std::error::Error as StdError;
use std::fmt::{self, Write as _};
use std::fs;
use std::io;
use std::ops::Range;
use std::path::{Path, PathBuf};
use std::sync::Arc;

use annotate_snippets::{AnnotationKind, Level, Renderer, Snippet, renderer::DecorStyle};
use quote::quote;
use rorolala_utils_lazyffi_core::{STRING_REPR, for_each_scalar, type_name, value_name};
use syn::{
    Attribute, Fields, FnArg, Item, ItemConst, ItemFn, ItemStruct, Pat, ReturnType, Type,
    spanned::Spanned,
};

/// File name of the generated header.
pub const HEADER_NAME: &str = "rorolala_ffi.h";

/// Renders the scalar types handed over by `for_each_scalar!` as a name array.
macro_rules! scalar_names {
    ($($scalar:ident),* $(,)?) => {
        &[$(stringify!($scalar)),*]
    };
}

/// Names of the scalar types whose repr is themselves.
///
/// Taken from `lazyffi-core`, so this list cannot drift from the conversions
/// `builtin` actually implements.
const SCALAR_NAMES: &[&str] = for_each_scalar!(scalar_names);

/// Include guard used in the generated header.
const INCLUDE_GUARD: &str = "ROROLALA_FFI_H";

/// Comment written at the top of every generated header.
const BANNER: &str = "\
/*!
 * This file is automatically generated by rorolala-dev-bindgen.
 * DO NOT EDIT THIS FILE MANUALLY.
 *
 * All string-returning functions allocate memory that must be freed using
 * ffi_free_string().
 */
";

/// Everything one generation run needs.
#[derive(Debug)]
pub struct Config<'a> {
    /// Directories scanned recursively for `#[lazyffi]` items.
    pub source_roots: &'a [PathBuf],
    /// Directory the header is written into; created when missing.
    pub output_dir: &'a Path,
}

/// A Rust type that has no repr-C sibling, so its item cannot be exported.
#[derive(Debug)]
pub struct Unresolved {
    /// Source file the item lives in.
    pub path: PathBuf,
    /// Full text of that file, kept for the diagnostic.
    pub source: String,
    /// 1-based line the item starts on.
    pub line: usize,
    /// Name of the item being rendered.
    pub item: String,
    /// The type that could not be resolved.
    pub ty: String,
}

/// What can go wrong while generating the header.
#[derive(Debug)]
pub enum Error {
    /// A source file could not be read, or the header could not be written.
    Io {
        /// The offending path.
        path: PathBuf,
        /// The underlying error.
        source: io::Error,
    },
    /// A source file could not be parsed as Rust.
    Parse {
        /// The offending path.
        path: PathBuf,
        /// The underlying error.
        source: syn::Error,
    },
    /// Types were found that have no repr-C sibling.
    Unresolved(Vec<Unresolved>),
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(formatter, "{}: {source}", path.display()),
            Self::Parse { path, source } => write!(formatter, "{}: {source}", path.display()),
            Self::Unresolved(diagnostics) => formatter.write_str(&render_diagnostics(diagnostics)),
        }
    }
}

impl StdError for Error {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Parse { source, .. } => Some(source),
            Self::Unresolved(_) => None,
        }
    }
}

/// Generates the header and returns the path it was written to.
///
/// # Errors
///
/// Fails when a source file cannot be read or parsed, when an item uses a type
/// that has no repr-C sibling, or when the header cannot be written into
/// [`Config::output_dir`].
pub fn generate(config: &Config<'_>) -> Result<PathBuf, Error> {
    let mut exports = Exports::default();
    for root in config.source_roots {
        scan_dir(root, &mut exports)?;
    }

    let header = render(&exports).map_err(Error::Unresolved)?;

    fs::create_dir_all(config.output_dir).map_err(|source| Error::Io {
        path: config.output_dir.to_path_buf(),
        source,
    })?;

    let path = config.output_dir.join(HEADER_NAME);
    fs::write(&path, header).map_err(|source| Error::Io {
        path: path.clone(),
        source,
    })?;

    Ok(path)
}

/// Where an item was read from, kept so diagnostics can point back at it.
#[derive(Clone)]
struct Origin {
    /// Source file.
    path: PathBuf,
    /// Full text of that file.
    source: Arc<String>,
}

/// The `#[lazyffi]` items collected from the sources.
#[derive(Default)]
struct Exports {
    /// Exported constants.
    constants: Vec<(ItemConst, Origin)>,
    /// Exported structs.
    structs: Vec<(ItemStruct, Origin)>,
    /// Exported functions.
    functions: Vec<(ItemFn, Origin)>,
}

/// Scans `dir` recursively, collecting `#[lazyffi]` items.
fn scan_dir(dir: &Path, exports: &mut Exports) -> Result<(), Error> {
    let entries = fs::read_dir(dir).map_err(|source| Error::Io {
        path: dir.to_path_buf(),
        source,
    })?;

    let mut paths = Vec::new();
    for entry in entries {
        let entry = entry.map_err(|source| Error::Io {
            path: dir.to_path_buf(),
            source,
        })?;
        paths.push(entry.path());
    }
    paths.sort();

    for path in paths {
        if path.is_dir() {
            scan_dir(&path, exports)?;
        } else if path.extension().is_some_and(|extension| extension == "rs") {
            scan_file(&path, exports)?;
        }
    }

    Ok(())
}

/// Parses one source file and collects its `#[lazyffi]` items.
fn scan_file(path: &Path, exports: &mut Exports) -> Result<(), Error> {
    let source = fs::read_to_string(path).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })?;
    let file = syn::parse_file(&source).map_err(|source| Error::Parse {
        path: path.to_path_buf(),
        source,
    })?;

    let origin = Origin {
        path: path.to_path_buf(),
        source: Arc::new(source),
    };
    collect_items(&file.items, &origin, exports);
    Ok(())
}

/// Collects `#[lazyffi]` items, descending into inline modules.
fn collect_items(items: &[Item], origin: &Origin, exports: &mut Exports) {
    for item in items {
        match item {
            Item::Mod(module) => {
                if let Some((_, inner)) = &module.content {
                    collect_items(inner, origin, exports);
                }
            }
            Item::Const(item) if has_lazyffi(&item.attrs) => {
                exports.constants.push((item.clone(), origin.clone()));
            }
            Item::Struct(item) if has_lazyffi(&item.attrs) => {
                exports.structs.push((item.clone(), origin.clone()));
            }
            Item::Fn(item) if has_lazyffi(&item.attrs) => {
                exports.functions.push((item.clone(), origin.clone()));
            }
            _ => {}
        }
    }
}

/// Whether an item carries `#[lazyffi]`, in any of its spellings.
fn has_lazyffi(attrs: &[Attribute]) -> bool {
    attrs.iter().any(|attr| {
        attr.path()
            .segments
            .last()
            .is_some_and(|segment| segment.ident == "lazyffi")
    })
}

/// Reads `export = <Name>` from the `#[lazyffi]` attribute, if present.
///
/// This parser is a deliberate second copy of the one in
/// `rorolala-utils-lazyffi-macros`; see the crate docs for why the two cannot be
/// merged, and mind both when adding attribute arguments.
fn export_override(attrs: &[Attribute]) -> Option<String> {
    for attr in attrs
        .iter()
        .filter(|attr| has_lazyffi(std::slice::from_ref(*attr)))
    {
        let mut name = None;
        let _ = attr.parse_nested_meta(|meta| {
            if !meta.path.is_ident("export") {
                return Ok(());
            }
            let value = meta.value()?;
            if let Ok(literal) = value.parse::<syn::LitStr>() {
                name = Some(literal.value());
            } else if let Ok(ident) = value.parse::<syn::Ident>() {
                name = Some(ident.to_string());
            } else {
                return Err(meta.error("expected an identifier or a string literal"));
            }
            Ok(())
        });
        if name.is_some() {
            return name;
        }
    }

    None
}

/// The repr-C sibling of every type that has one, keyed by the Rust type name.
type ReprMap = BTreeMap<String, String>;

/// Builds the Rust type name → repr-C type map.
///
/// The built-in types come from `lazyffi-core`, so they match what `builtin`
/// actually implements; every `#[lazyffi]` struct maps to the repr type its
/// invocation generates.
fn repr_map(exports: &Exports) -> ReprMap {
    let mut reprs = ReprMap::new();

    for scalar in SCALAR_NAMES {
        reprs.insert((*scalar).to_string(), (*scalar).to_string());
    }
    reprs.insert("String".to_string(), STRING_REPR.to_string());

    for (item, _) in &exports.structs {
        let rust_name = item.ident.to_string();
        let default = type_name(&rust_name);
        let name = export_override(&item.attrs).unwrap_or(default);
        reprs.insert(rust_name, name);
    }

    reprs
}

/// Resolves the repr-C sibling of a Rust type.
fn repr_of(ty: &Type, reprs: &ReprMap) -> Option<String> {
    if let Type::Path(path) = ty
        && let Some(ident) = path.path.get_ident()
    {
        return reprs.get(&ident.to_string()).cloned();
    }

    None
}

/// C spelling of a repr type.
fn c_type(repr: &str, reprs: &ReprMap) -> Option<String> {
    if let Some(scalar) = scalar_c_type(repr) {
        return Some(scalar.to_string());
    }

    if repr == STRING_REPR {
        return Some("char *".to_string());
    }

    if let Some(inner) = repr.strip_prefix("*mut ") {
        return Some(format!("{} *", c_type(inner, reprs)?));
    }

    // A generated repr struct keeps its Rust name in C.
    if reprs.values().any(|value| value == repr) {
        return Some(repr.to_string());
    }

    None
}

/// C spelling of the scalar types whose repr is themselves.
fn scalar_c_type(rust: &str) -> Option<&'static str> {
    Some(match rust {
        "bool" => "bool",
        // A Rust `char` is a 32-bit scalar, so it shares `u32`'s C spelling.
        "char" | "u32" => "uint32_t",
        "f32" => "float",
        "f64" => "double",
        "i8" => "int8_t",
        "i16" => "int16_t",
        "i32" => "int32_t",
        "i64" => "int64_t",
        "i128" => "__int128",
        "isize" => "intptr_t",
        "u8" => "uint8_t",
        "u16" => "uint16_t",
        "u64" => "uint64_t",
        "u128" => "unsigned __int128",
        "usize" => "uintptr_t",
        _ => return None,
    })
}

/// Whether a type is a reference to `str`.
fn is_str_ref(ty: &Type) -> bool {
    if let Type::Reference(reference) = ty
        && let Type::Path(inner) = &*reference.elem
    {
        return inner.path.is_ident("str");
    }

    false
}

/// Records that `ty` inside `item` has no repr-C sibling.
fn unresolved(diagnostics: &mut Vec<Unresolved>, origin: &Origin, item: &str, ty: &Type) {
    diagnostics.push(Unresolved {
        path: origin.path.clone(),
        source: origin.source.as_ref().clone(),
        line: ty.span().start().line,
        item: item.to_string(),
        // `quote!` renders paths with padding (`core :: net :: IpAddr`); C users
        // expect the compact spelling.
        ty: quote!(#ty).to_string().replace(" :: ", "::"),
    });
}

/// Renders the whole header, or reports every type it could not resolve.
fn render(exports: &Exports) -> Result<String, Vec<Unresolved>> {
    let reprs = repr_map(exports);
    let mut diagnostics = Vec::new();
    let mut out = String::from(BANNER);

    let _ = writeln!(out, "\n#ifndef {INCLUDE_GUARD}");
    let _ = writeln!(out, "#define {INCLUDE_GUARD}\n");
    out.push_str(
        "#include <stdarg.h>\n#include <stdbool.h>\n#include <stdint.h>\n#include <stdlib.h>\n\n",
    );

    for (item, origin) in &exports.constants {
        render_const(&mut out, item, origin, &reprs, &mut diagnostics);
    }
    for (item, origin) in &exports.structs {
        render_struct(&mut out, item, origin, &reprs, &mut diagnostics);
    }
    for (item, origin) in &exports.functions {
        render_function(&mut out, item, origin, &reprs, &mut diagnostics);
    }

    if !diagnostics.is_empty() {
        return Err(diagnostics);
    }

    let _ = writeln!(out, "#endif  /* {INCLUDE_GUARD} */");
    Ok(out)
}

/// Renders one exported constant.
fn render_const(
    out: &mut String,
    item: &ItemConst,
    origin: &Origin,
    reprs: &ReprMap,
    diagnostics: &mut Vec<Unresolved>,
) {
    let rust_name = item.ident.to_string();
    let default = value_name(&rust_name);
    let export = export_override(&item.attrs).unwrap_or(default);

    if is_str_ref(&item.ty) {
        let _ = writeln!(out, "char *{export}(void);\n");
        return;
    }

    let Some(repr) = repr_of(&item.ty, reprs) else {
        unresolved(diagnostics, origin, &rust_name, &item.ty);
        return;
    };
    let Some(c_type) = c_type(&repr, reprs) else {
        unresolved(diagnostics, origin, &rust_name, &item.ty);
        return;
    };

    let _ = writeln!(out, "extern const {c_type} {export};\n");
}

/// Renders the repr-C sibling of one exported struct.
fn render_struct(
    out: &mut String,
    item: &ItemStruct,
    origin: &Origin,
    reprs: &ReprMap,
    diagnostics: &mut Vec<Unresolved>,
) {
    let rust_name = item.ident.to_string();
    let Some(repr) = reprs.get(&rust_name).cloned() else {
        return;
    };
    let Fields::Named(named) = &item.fields else {
        return;
    };

    let _ = writeln!(out, "typedef struct {repr} {{");
    for field in &named.named {
        let Some(name) = field.ident.as_ref() else {
            continue;
        };
        let Some(field_repr) = repr_of(&field.ty, reprs) else {
            unresolved(
                diagnostics,
                origin,
                &format!("{rust_name}.{name}"),
                &field.ty,
            );
            continue;
        };
        let Some(c_type) = c_type(&field_repr, reprs) else {
            unresolved(
                diagnostics,
                origin,
                &format!("{rust_name}.{name}"),
                &field.ty,
            );
            continue;
        };
        let _ = writeln!(out, "  {c_type} {name};");
    }
    let _ = writeln!(out, "}} {repr};\n");
}

/// Renders the wrapper of one exported function.
fn render_function(
    out: &mut String,
    item: &ItemFn,
    origin: &Origin,
    reprs: &ReprMap,
    diagnostics: &mut Vec<Unresolved>,
) {
    let rust_name = item.sig.ident.to_string();
    let default = value_name(&rust_name);
    let export = export_override(&item.attrs).unwrap_or(default);

    let mut params = Vec::new();
    for input in &item.sig.inputs {
        let FnArg::Typed(pat_type) = input else {
            continue;
        };
        let Pat::Ident(pat_ident) = &*pat_type.pat else {
            continue;
        };

        let repr = match &*pat_type.ty {
            Type::Reference(reference) => {
                let Some(inner) = repr_of(&reference.elem, reprs) else {
                    unresolved(diagnostics, origin, &rust_name, &reference.elem);
                    continue;
                };
                format!("*mut {inner}")
            }
            other => {
                let Some(repr) = repr_of(other, reprs) else {
                    unresolved(diagnostics, origin, &rust_name, other);
                    continue;
                };
                repr
            }
        };

        let Some(c_type) = c_type(&repr, reprs) else {
            unresolved(diagnostics, origin, &rust_name, &pat_type.ty);
            continue;
        };
        params.push(format!("{c_type} {}", pat_ident.ident));
    }

    let returns = match &item.sig.output {
        ReturnType::Default => "void".to_string(),
        ReturnType::Type(_, ty) => {
            let Some(repr) = repr_of(ty, reprs) else {
                unresolved(diagnostics, origin, &rust_name, ty);
                return;
            };
            let Some(c_type) = c_type(&repr, reprs) else {
                unresolved(diagnostics, origin, &rust_name, ty);
                return;
            };
            c_type
        }
    };

    if params.is_empty() {
        let _ = writeln!(out, "{returns} {export}(void);\n");
    } else {
        let _ = writeln!(out, "{returns} {export}({});\n", params.join(", "));
    }
}

/// Byte offset at which a 1-based `line` starts in `source`.
fn line_offset(source: &str, line: usize) -> Range<usize> {
    let mut offset = 0;
    for (index, text) in source.split_inclusive('\n').enumerate() {
        if index + 1 == line {
            let length = text.trim_end_matches('\n').len();
            return offset..offset + length;
        }
        offset += text.len();
    }

    0..0
}

/// Renders [`Unresolved`] diagnostics with `annotate-snippets`.
fn render_diagnostics(diagnostics: &[Unresolved]) -> String {
    let renderer = Renderer::styled().decor_style(DecorStyle::Unicode);
    let mut out = String::new();

    for diagnostic in diagnostics {
        let report = &[Level::ERROR
            .primary_title(format!("`{}` cannot be exported", diagnostic.item))
            .element(
                Snippet::source(&diagnostic.source)
                    .line_start(1)
                    .path(diagnostic.path.display().to_string())
                    .annotation(
                        AnnotationKind::Primary
                            .span(line_offset(&diagnostic.source, diagnostic.line))
                            .label(format!("`{}` has no repr-C sibling", diagnostic.ty)),
                    ),
            )];
        out.push_str(&renderer.render(report));
    }

    out
}
