// <auto-generated />
//
// The C ABI of `librorolala`, bound from `rorolala_ffi.h` by `rorolala-dev-rsharp-bindgen`. DO NOT
// EDIT — the build rewrites this file, and an edit is lost with it.
//
// Every member is internal: this is the boilerplate half of the library, and the more OOP layer a
// caller is meant to use is hand-written over it. What crosses is raw — every pointer is a `nint`,
// and a string comes back as a pointer to release with `free_string` — so that layer owns the
// marshalling.

#nullable disable
#pragma warning disable

using System.Runtime.InteropServices;

namespace RolaSharp;

/// <summary>
/// Which side of a `Result` a `RorolalaResult` carries.
/// </summary>
internal enum RorolalaResultTag : int
{
    /// <summary>
    /// The call succeeded, and the payload is its value.
    /// </summary>
    RorolalaResult_Ok = 0,
    /// <summary>
    /// The call failed, and the payload is the error.
    /// </summary>
    RorolalaResult_Err = 1,
}

/// <summary>
/// What a fallible export hands back.
///
/// The payload is owned by the caller: read the tag to learn which side it is,
/// cast it to the type the function names for that side, and release it with
/// that type's own `free_*`. It is null when there is nothing to carry.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RorolalaResult
{
    public RorolalaResultTag tag;
    public nint payload;
}

internal enum RolaAuthErrorTag : int
{
    /// <summary>
    /// A key or signature was not the shape its algorithm states.
    /// </summary>
    RolaAuthError_Malformed = 0,
    /// <summary>
    /// A signature did not verify under the key it was checked against.
    /// </summary>
    RolaAuthError_BadSignature = 1,
    /// <summary>
    /// The peer proved an identity other than the one that was expected.
    /// </summary>
    RolaAuthError_UnexpectedIdentity = 2,
    /// <summary>
    /// A handshake did not follow the protocol: a message was out of order, named a suite
    /// </summary>
    RolaAuthError_Handshake = 3,
    /// <summary>
    /// A record did not decrypt: it was altered, reordered, or never a record at all.
    /// </summary>
    RolaAuthError_BadRecord = 4,
    /// <summary>
    /// The underlying stream failed.
    /// </summary>
    RolaAuthError_Io = 5,
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaAuthErrorPayload
{
    /// <summary>
    /// The underlying stream failed.
    /// </summary>
    [FieldOffset(0)]
    public nint Io;
}

/// <summary>
/// What can go wrong while reading an identity, proving one, or running a session.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaAuthError
{
    public RolaAuthErrorTag tag;
    public RolaAuthErrorPayload payload;
}

/// <summary>
/// What an I/O failure was, in `std`'s spelling.
/// </summary>
internal enum RolaIoErrorKind : int
{
    /// <summary>
    /// An entity was not found, often a file.
    /// </summary>
    RolaIoErrorKind_NotFound = 0,
    /// <summary>
    /// The operation lacked the necessary privileges to complete.
    /// </summary>
    RolaIoErrorKind_PermissionDenied = 1,
    /// <summary>
    /// The connection was refused by the remote server.
    /// </summary>
    RolaIoErrorKind_ConnectionRefused = 2,
    /// <summary>
    /// The connection was reset by the remote server.
    /// </summary>
    RolaIoErrorKind_ConnectionReset = 3,
    /// <summary>
    /// The remote host is not reachable.
    /// </summary>
    RolaIoErrorKind_HostUnreachable = 4,
    /// <summary>
    /// The network is not reachable.
    /// </summary>
    RolaIoErrorKind_NetworkUnreachable = 5,
    /// <summary>
    /// The connection was aborted by the remote server.
    /// </summary>
    RolaIoErrorKind_ConnectionAborted = 6,
    /// <summary>
    /// The connection has not been established yet.
    /// </summary>
    RolaIoErrorKind_NotConnected = 7,
    /// <summary>
    /// The address is in use.
    /// </summary>
    RolaIoErrorKind_AddrInUse = 8,
    /// <summary>
    /// The address is not available.
    /// </summary>
    RolaIoErrorKind_AddrNotAvailable = 9,
    /// <summary>
    /// The network is down.
    /// </summary>
    RolaIoErrorKind_NetworkDown = 10,
    /// <summary>
    /// The pipe was closed, usually by writing to one whose read end is gone.
    /// </summary>
    RolaIoErrorKind_BrokenPipe = 11,
    /// <summary>
    /// An entity already exists, often a file.
    /// </summary>
    RolaIoErrorKind_AlreadyExists = 12,
    /// <summary>
    /// The operation would have to block, and was asked not to.
    /// </summary>
    RolaIoErrorKind_WouldBlock = 13,
    /// <summary>
    /// A filesystem object is, unexpectedly, not a directory.
    /// </summary>
    RolaIoErrorKind_NotAdirectory = 14,
    /// <summary>
    /// A filesystem object is, unexpectedly, a directory.
    /// </summary>
    RolaIoErrorKind_IsAdirectory = 15,
    /// <summary>
    /// A directory is not empty.
    /// </summary>
    RolaIoErrorKind_DirectoryNotEmpty = 16,
    /// <summary>
    /// The filesystem is read-only.
    /// </summary>
    RolaIoErrorKind_ReadOnlyFilesystem = 17,
    /// <summary>
    /// The network file handle the operation was given is stale.
    /// </summary>
    RolaIoErrorKind_StaleNetworkFileHandle = 18,
    /// <summary>
    /// A parameter was incorrect.
    /// </summary>
    RolaIoErrorKind_InvalidInput = 19,
    /// <summary>
    /// Data that was not valid for the operation was received.
    /// </summary>
    RolaIoErrorKind_InvalidData = 20,
    /// <summary>
    /// An operation timed out.
    /// </summary>
    RolaIoErrorKind_TimedOut = 21,
    /// <summary>
    /// A write returned zero when more was expected.
    /// </summary>
    RolaIoErrorKind_WriteZero = 22,
    /// <summary>
    /// The filesystem is full.
    /// </summary>
    RolaIoErrorKind_StorageFull = 23,
    /// <summary>
    /// The stream cannot be seeked.
    /// </summary>
    RolaIoErrorKind_NotSeekable = 24,
    /// <summary>
    /// A filesystem quota was exceeded.
    /// </summary>
    RolaIoErrorKind_QuotaExceeded = 25,
    /// <summary>
    /// The file is larger than the filesystem can hold.
    /// </summary>
    RolaIoErrorKind_FileTooLarge = 26,
    /// <summary>
    /// A resource is busy.
    /// </summary>
    RolaIoErrorKind_ResourceBusy = 27,
    /// <summary>
    /// An executable file is busy, usually because it is being written to.
    /// </summary>
    RolaIoErrorKind_ExecutableFileBusy = 28,
    /// <summary>
    /// An operation would deadlock.
    /// </summary>
    RolaIoErrorKind_Deadlock = 29,
    /// <summary>
    /// A move or copy between filesystems was attempted.
    /// </summary>
    RolaIoErrorKind_CrossesDevices = 30,
    /// <summary>
    /// A file has too many hard links.
    /// </summary>
    RolaIoErrorKind_TooManyLinks = 31,
    /// <summary>
    /// A filename is invalid.
    /// </summary>
    RolaIoErrorKind_InvalidFilename = 32,
    /// <summary>
    /// An argument list was longer than the limit allows.
    /// </summary>
    RolaIoErrorKind_ArgumentListTooLong = 33,
    /// <summary>
    /// The operation was interrupted before it completed, and may be retried.
    /// </summary>
    RolaIoErrorKind_Interrupted = 34,
    /// <summary>
    /// The operation is not supported.
    /// </summary>
    RolaIoErrorKind_Unsupported = 35,
    /// <summary>
    /// An end of file was reached when it was not expected.
    /// </summary>
    RolaIoErrorKind_UnexpectedEof = 36,
    /// <summary>
    /// An operation ran out of memory.
    /// </summary>
    RolaIoErrorKind_OutOfMemory = 37,
    /// <summary>
    /// A failure that falls under no other kind: what `std` does not classify, and
    /// </summary>
    RolaIoErrorKind_Other = 38,
}

/// <summary>
/// The role by which a source object points at a target key
/// </summary>
internal enum RolaInverseEdge : int
{
    /// <summary>
    /// A Variant's storage address: the content the variant was made of.
    /// </summary>
    RolaInverseEdge_Storage = 0,
    /// <summary>
    /// A Variant's base Version.
    /// </summary>
    RolaInverseEdge_Base = 1,
    /// <summary>
    /// The Variant a Variant merges in.
    /// </summary>
    RolaInverseEdge_Join = 2,
    /// <summary>
    /// A Variant's Creator.
    /// </summary>
    RolaInverseEdge_Creator = 3,
    /// <summary>
    /// A Variant's Message.
    /// </summary>
    RolaInverseEdge_Message = 4,
    /// <summary>
    /// A Version's Variant.
    /// </summary>
    RolaInverseEdge_Variant = 5,
}

internal enum RolaInverseIndexErrorTag : int
{
    /// <summary>
    /// The index it is built from could not be read.
    /// </summary>
    RolaInverseIndexError_Read = 0,
    /// <summary>
    /// What is there does not read as an inverse index this build knows.
    /// </summary>
    RolaInverseIndexError_Malformed = 1,
    /// <summary>
    /// The inverse index could not be written.
    /// </summary>
    RolaInverseIndexError_Io = 2,
}

[StructLayout(LayoutKind.Sequential)]
internal struct RolaVCSIndexReadingErrorCorrupt
{
    /// <summary>
    /// The key what came back does not hash to.
    /// </summary>
    public nint key;
}

[StructLayout(LayoutKind.Sequential)]
internal struct RolaVCSIndexReadingErrorNotFound
{
    /// <summary>
    /// The key nothing is stored under.
    /// </summary>
    public nint key;
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaVCSIndexReadingErrorPayload
{
    /// <summary>
    /// Nothing is stored under the key.
    /// </summary>
    [FieldOffset(0)]
    public RolaVCSIndexReadingErrorNotFound NotFound;
    /// <summary>
    /// What came back does not hash to the key it was read under.
    /// </summary>
    [FieldOffset(0)]
    public RolaVCSIndexReadingErrorCorrupt Corrupt;
    /// <summary>
    /// The index itself failed.
    /// </summary>
    [FieldOffset(0)]
    public nint Io;
}

internal enum RolaVCSIndexReadingErrorTag : int
{
    /// <summary>
    /// Nothing is stored under the key.
    /// </summary>
    RolaVCSIndexReadingError_NotFound = 0,
    /// <summary>
    /// What is stored does not read as an index object this build knows.
    /// </summary>
    RolaVCSIndexReadingError_Malformed = 1,
    /// <summary>
    /// What came back does not hash to the key it was read under.
    /// </summary>
    RolaVCSIndexReadingError_Corrupt = 2,
    /// <summary>
    /// The index itself failed.
    /// </summary>
    RolaVCSIndexReadingError_Io = 3,
}

/// <summary>
/// What a read of the index failed with
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaVCSIndexReadingError
{
    public RolaVCSIndexReadingErrorTag tag;
    public RolaVCSIndexReadingErrorPayload payload;
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaInverseIndexErrorPayload
{
    /// <summary>
    /// The index it is built from could not be read.
    /// </summary>
    [FieldOffset(0)]
    public RolaVCSIndexReadingError Read;
    /// <summary>
    /// The inverse index could not be written.
    /// </summary>
    [FieldOffset(0)]
    public nint Io;
}

/// <summary>
/// What building the inverse index failed with
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaInverseIndexError
{
    public RolaInverseIndexErrorTag tag;
    public RolaInverseIndexErrorPayload payload;
}

internal enum RolaInverseIndexReadingErrorTag : int
{
    /// <summary>
    /// Nothing is stored under the key.
    /// </summary>
    RolaInverseIndexReadingError_NotFound = 0,
    /// <summary>
    /// What is stored is not the kind of object the question is about.
    /// </summary>
    RolaInverseIndexReadingError_Malformed = 1,
    /// <summary>
    /// Reading the index failed.
    /// </summary>
    RolaInverseIndexReadingError_Read = 2,
    /// <summary>
    /// The inverse index itself failed.
    /// </summary>
    RolaInverseIndexReadingError_Io = 3,
}

[StructLayout(LayoutKind.Sequential)]
internal struct RolaInverseIndexReadingErrorNotFound
{
    /// <summary>
    /// The key nothing is stored under.
    /// </summary>
    public nint key;
}

[StructLayout(LayoutKind.Sequential)]
internal struct RolaInverseIndexReadingErrorRead
{
    /// <summary>
    /// Why it failed.
    /// </summary>
    public nint cause;
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaInverseIndexReadingErrorPayload
{
    /// <summary>
    /// Nothing is stored under the key.
    /// </summary>
    [FieldOffset(0)]
    public RolaInverseIndexReadingErrorNotFound NotFound;
    /// <summary>
    /// Reading the index failed.
    /// </summary>
    [FieldOffset(0)]
    public RolaInverseIndexReadingErrorRead Read;
    /// <summary>
    /// The inverse index itself failed.
    /// </summary>
    [FieldOffset(0)]
    public nint Io;
}

/// <summary>
/// What a read through the inverse index failed with
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaInverseIndexReadingError
{
    public RolaInverseIndexReadingErrorTag tag;
    public RolaInverseIndexReadingErrorPayload payload;
}

internal enum RolaActionErrorTag : int
{
    /// <summary>
    /// The action context has no channel, so nothing can be exchanged with the peer.
    /// </summary>
    RolaActionError_NoChannel = 0,
    /// <summary>
    /// The side that owns a value held none to send, which its side should never do.
    /// </summary>
    RolaActionError_MissingValue = 1,
    /// <summary>
    /// An object the exchange was being made for was held by neither side, so there was
    /// </summary>
    RolaActionError_MissingObject = 2,
    /// <summary>
    /// A value was longer than a frame can carry.
    /// </summary>
    RolaActionError_ValueTooLarge = 3,
    /// <summary>
    /// The channel failed.
    /// </summary>
    RolaActionError_Io = 4,
    /// <summary>
    /// A value could not be encoded, or a frame could not be decoded.
    /// </summary>
    RolaActionError_Codec = 5,
    /// <summary>
    /// A store on one side could not produce or take what the exchange needed.
    /// </summary>
    RolaActionError_Store = 6,
    /// <summary>
    /// No action answers to the id asked for.
    /// </summary>
    RolaActionError_UnknownAction = 7,
    /// <summary>
    /// What an action produced could not be turned into JSON.
    /// </summary>
    RolaActionError_Json = 8,
    /// <summary>
    /// The target a caller named would not read as an address.
    /// </summary>
    RolaActionError_Addr = 9,
    /// <summary>
    /// The session could not be established: a key could not be read, the peer could not
    /// </summary>
    RolaActionError_Auth = 10,
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaActionErrorPayload
{
    /// <summary>
    /// The channel failed.
    /// </summary>
    [FieldOffset(0)]
    public nint Io;
    /// <summary>
    /// A value could not be encoded, or a frame could not be decoded.
    /// </summary>
    [FieldOffset(0)]
    public nint Codec;
    /// <summary>
    /// A store on one side could not produce or take what the exchange needed.
    /// </summary>
    [FieldOffset(0)]
    public nint Store;
    /// <summary>
    /// No action answers to the id asked for.
    /// </summary>
    [FieldOffset(0)]
    public uint UnknownAction;
    /// <summary>
    /// What an action produced could not be turned into JSON.
    /// </summary>
    [FieldOffset(0)]
    public nint Json;
    /// <summary>
    /// The target a caller named would not read as an address.
    /// </summary>
    [FieldOffset(0)]
    public nint Addr;
    /// <summary>
    /// The session could not be established: a key could not be read, the peer could not
    /// </summary>
    [FieldOffset(0)]
    public RolaAuthError Auth;
}

/// <summary>
/// Everything that can go wrong while an action runs.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaActionError
{
    public RolaActionErrorTag tag;
    public RolaActionErrorPayload payload;
}

/// <summary>
/// Represents an error that occurs during the creation of a Vault
/// </summary>
internal enum VaultCreationError : int
{
    /// <summary>
    /// Failure when the directory the Vault keeps its configuration in cannot be created
    /// </summary>
    VaultCreationError_DirCreateFailed = 0,
    /// <summary>
    /// Failure when the Layout the Vault keeps cannot be made
    /// </summary>
    VaultCreationError_LayoutCreateFailed = 1,
    /// <summary>
    /// Failure when reading the staging file to check if it already exists
    /// </summary>
    VaultCreationError_ConfigLocked = 2,
    /// <summary>
    /// Failure when rendering the default value into the configuration format
    /// </summary>
    VaultCreationError_ConfigRenderFailed = 3,
    /// <summary>
    /// Failure when writing the staging file
    /// </summary>
    VaultCreationError_ConfigStageFailed = 4,
    /// <summary>
    /// Failure when publishing (copying) the staging file to the configuration file
    /// </summary>
    VaultCreationError_ConfigPublishFailed = 5,
    /// <summary>
    /// Failure when the staging file cannot be rendered
    /// </summary>
    VaultCreationError_ConfigWriteRenderFailed = 6,
    /// <summary>
    /// Failure when the staging file cannot be written
    /// </summary>
    VaultCreationError_ConfigWriteStageFailed = 7,
    /// <summary>
    /// Failure with an unknown or unclassified cause
    /// </summary>
    VaultCreationError_UnknownError = 8,
}

/// <summary>
/// The error of reading an index object as a kind it is not
/// </summary>
internal enum RolaParseVCSIndexObjectError : int
{
    /// <summary>
    /// A Variant was expected, but a Version was found
    /// </summary>
    RolaParseVCSIndexObjectError_ExpectVariant = 0,
    /// <summary>
    /// A Version was expected, but a Variant was found
    /// </summary>
    RolaParseVCSIndexObjectError_ExpectVersion = 1,
    /// <summary>
    /// A Creator was expected, but another kind of object was found
    /// </summary>
    RolaParseVCSIndexObjectError_ExpectCreator = 2,
    /// <summary>
    /// A Message was expected, but another kind of object was found
    /// </summary>
    RolaParseVCSIndexObjectError_ExpectMessage = 3,
}

internal enum RolaVCSIndexWritingErrorTag : int
{
    /// <summary>
    /// What was handed over does not encode as an index object.
    /// </summary>
    RolaVCSIndexWritingError_Malformed = 0,
    /// <summary>
    /// The index itself failed.
    /// </summary>
    RolaVCSIndexWritingError_Io = 1,
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaVCSIndexWritingErrorPayload
{
    /// <summary>
    /// The index itself failed.
    /// </summary>
    [FieldOffset(0)]
    public nint Io;
}

/// <summary>
/// What a write to the index failed with
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaVCSIndexWritingError
{
    public RolaVCSIndexWritingErrorTag tag;
    public RolaVCSIndexWritingErrorPayload payload;
}

internal enum RolaVCSIndexObjectTag : int
{
    /// <summary>
    /// A Variant object
    /// </summary>
    RolaVCSIndexObject_Variant = 0,
    /// <summary>
    /// A Version object
    /// </summary>
    RolaVCSIndexObject_Version = 1,
    /// <summary>
    /// A Creator object
    /// </summary>
    RolaVCSIndexObject_Creator = 2,
    /// <summary>
    /// A Message object
    /// </summary>
    RolaVCSIndexObject_Message = 3,
}

[StructLayout(LayoutKind.Explicit)]
internal struct RolaVCSIndexObjectPayload
{
    /// <summary>
    /// A Variant object
    /// </summary>
    [FieldOffset(0)]
    public nint Variant;
    /// <summary>
    /// A Version object
    /// </summary>
    [FieldOffset(0)]
    public nint Version;
    /// <summary>
    /// A Creator object
    /// </summary>
    [FieldOffset(0)]
    public nint Creator;
    /// <summary>
    /// A Message object
    /// </summary>
    [FieldOffset(0)]
    public nint Message;
}

/// <summary>
/// An object a version control index holds
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct RolaVCSIndexObject
{
    public RolaVCSIndexObjectTag tag;
    public RolaVCSIndexObjectPayload payload;
}

/// <summary>
/// The kind of a Variant
/// </summary>
internal enum RolaVariantType : int
{
    /// <summary>
    /// Progressive: based on one Version and pointing at one stored entry
    /// </summary>
    RolaVariantType_Progressive = 0,
    /// <summary>
    /// Merge: based on one Version and joining in an existing variant
    /// </summary>
    RolaVariantType_Merge = 1,
}

/// <summary>
/// Represents an error that occurs during the creation of a Workspace
/// </summary>
internal enum WorkspaceCreationError : int
{
    /// <summary>
    /// Failure when the directory the Workspace keeps its data in cannot be created
    /// </summary>
    WorkspaceCreationError_DataDirCreateFailed = 0,
    /// <summary>
    /// Failure when reading the staging file to check if it already exists
    /// </summary>
    WorkspaceCreationError_ConfigLocked = 1,
    /// <summary>
    /// Failure when rendering the default value into the configuration format
    /// </summary>
    WorkspaceCreationError_ConfigRenderFailed = 2,
    /// <summary>
    /// Failure when writing the staging file
    /// </summary>
    WorkspaceCreationError_ConfigStageFailed = 3,
    /// <summary>
    /// Failure when publishing (copying) the staging file to the configuration file
    /// </summary>
    WorkspaceCreationError_ConfigPublishFailed = 4,
    /// <summary>
    /// Failure when the staging file cannot be rendered
    /// </summary>
    WorkspaceCreationError_ConfigWriteRenderFailed = 5,
    /// <summary>
    /// Failure when the staging file cannot be written
    /// </summary>
    WorkspaceCreationError_ConfigWriteStageFailed = 6,
    /// <summary>
    /// Failure with an unknown or unclassified cause
    /// </summary>
    WorkspaceCreationError_UnknownError = 7,
}

/// <summary>
/// Why the filesystem refused, as far as this crate tells the reasons apart.
/// </summary>
internal enum ConfigureErrorReason : int
{
    /// <summary>
    /// Nothing is there.
    /// </summary>
    ConfigureErrorReason_Missing = 0,
    /// <summary>
    /// There, but not allowed.
    /// </summary>
    ConfigureErrorReason_Denied = 1,
    /// <summary>
    /// There, but not what the operation needed — a directory where a file was wanted,
    /// </summary>
    ConfigureErrorReason_WrongKind = 2,
    /// <summary>
    /// There, but in use, or otherwise busy.
    /// </summary>
    ConfigureErrorReason_Busy = 3,
    /// <summary>
    /// Something else, which this crate does not tell apart.
    /// </summary>
    ConfigureErrorReason_Other = 4,
}

internal enum ConfigureErrorTag : int
{
    /// <summary>
    /// The file could not be read.
    /// </summary>
    ConfigureError_Read = 0,
    /// <summary>
    /// The staging file could not be written.
    /// </summary>
    ConfigureError_Stage = 1,
    /// <summary>
    /// The staging file could not replace the original.
    /// </summary>
    ConfigureError_Publish = 2,
    /// <summary>
    /// The file's contents do not parse as the configuration type.
    /// </summary>
    ConfigureError_Parse = 3,
    /// <summary>
    /// The configuration could not be rendered in the file's format.
    /// </summary>
    ConfigureError_Render = 4,
    /// <summary>
    /// A staging file was already there, so an earlier edit was never published.
    /// </summary>
    ConfigureError_Locked = 5,
}

[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureErrorRead
{
    /// <summary>
    /// The file that could not be read.
    /// </summary>
    public nint file;
    /// <summary>
    /// Why not.
    /// </summary>
    public ConfigureErrorReason reason;
}

[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureErrorStage
{
    /// <summary>
    /// The file that was being read, or edited.
    /// </summary>
    public nint file;
    /// <summary>
    /// The staging file that could not be written.
    /// </summary>
    public nint @lock;
    /// <summary>
    /// Why not.
    /// </summary>
    public ConfigureErrorReason reason;
}

[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureErrorPublish
{
    /// <summary>
    /// The file that was left as it was.
    /// </summary>
    public nint file;
    /// <summary>
    /// The staging file that is still staged.
    /// </summary>
    public nint @lock;
    /// <summary>
    /// Why not.
    /// </summary>
    public ConfigureErrorReason reason;
}

[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureErrorParse
{
    /// <summary>
    /// The file that does not parse.
    /// </summary>
    public nint file;
    /// <summary>
    /// 1-based line the parser stopped at, or 0 when it named no position.
    /// </summary>
    public uint line;
    /// <summary>
    /// 1-based column the parser stopped at, or 0 when it named no position.
    /// </summary>
    public uint column;
}

[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureErrorRender
{
    /// <summary>
    /// The file the rendering was for.
    /// </summary>
    public nint file;
}

[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureErrorLocked
{
    /// <summary>
    /// The file the read was for.
    /// </summary>
    public nint file;
    /// <summary>
    /// The staging file left behind by whoever got there first.
    /// </summary>
    public nint @lock;
}

[StructLayout(LayoutKind.Explicit)]
internal struct ConfigureErrorPayload
{
    /// <summary>
    /// The file could not be read.
    /// </summary>
    [FieldOffset(0)]
    public ConfigureErrorRead Read;
    /// <summary>
    /// The staging file could not be written.
    /// </summary>
    [FieldOffset(0)]
    public ConfigureErrorStage Stage;
    /// <summary>
    /// The staging file could not replace the original.
    /// </summary>
    [FieldOffset(0)]
    public ConfigureErrorPublish Publish;
    /// <summary>
    /// The file's contents do not parse as the configuration type.
    /// </summary>
    [FieldOffset(0)]
    public ConfigureErrorParse Parse;
    /// <summary>
    /// The configuration could not be rendered in the file's format.
    /// </summary>
    [FieldOffset(0)]
    public ConfigureErrorRender Render;
    /// <summary>
    /// A staging file was already there, so an earlier edit was never published.
    /// </summary>
    [FieldOffset(0)]
    public ConfigureErrorLocked Locked;
}

/// <summary>
/// What can go wrong while reading, staging or publishing a configuration file.
/// </summary>
[StructLayout(LayoutKind.Sequential)]
internal struct ConfigureError
{
    public ConfigureErrorTag tag;
    public ConfigureErrorPayload payload;
}

internal static partial class RorolalaBinding
{
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_string(nint @string);

    /// <summary>
    /// Hash salt for Variant
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_SALT_VRT();

    /// <summary>
    /// Hash salt for Version
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_SALT_VER();

    /// <summary>
    /// Hash salt for Layout
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_SALT_LYT();

    /// <summary>
    /// Hash salt for Creator
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_SALT_CRT();

    /// <summary>
    /// Hash salt for Message
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_SALT_MSG();

    /// <summary>
    /// The Workspace's data directory, inside the workspace root
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_DATA_DIR();

    /// <summary>
    /// Path to the Workspace configuration file, inside its data directory
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_CONFIG_PATH();

    /// <summary>
    /// Path, inside the Workspace's data directory, where its keys are kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_KEYS_DIR();

    /// <summary>
    /// Path, inside the Workspace's data directory, where its Layouts are kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_LAYOUTS_DIR();

    /// <summary>
    /// Path to the file naming the Layout a Workspace has checked out
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_LAYOUT_PATH();

    /// <summary>
    /// Path to the file a run opens in an editor to write what it is recording
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_EDITING_PATH();

    /// <summary>
    /// Path, inside the Workspace's data directory, where what a Layout's analysis is kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_CACHE_DIR();

    /// <summary>
    /// Path, inside the Workspace's cache, where remote Layouts are kept read-only
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_READONLY_LAYOUTS_DIR();

    /// <summary>
    /// The file, inside a Layout's directory, naming the upstream Vault it tracks
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_LAYOUT_TRACK_FILE();

    /// <summary>
    /// Path, inside the Vault's root, where its single Layout is kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_LAYOUT_DIR();

    /// <summary>
    /// The name a Workspace's first Layout is commonly given
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_DEFAULT_LAYOUT_NAME();

    /// <summary>
    /// The name a Vault's single Layout is known by
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_LAYOUT_NAME();

    /// <summary>
    /// Path to the Vault configuration file, inside the vault root
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_CONFIG_PATH();

    /// <summary>
    /// Path, inside the Vault, where its keys are kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_KEYS_DIR();

    /// <summary>
    /// Path, inside the Vault's root, where the Vaults it holds are kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_VAULTS_DIR();

    /// <summary>
    /// Path to the storage configuration file, inside the storage root
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_STORAGE_CONFIG_PATH();

    /// <summary>
    /// Path, inside the Workspace's data directory, where its store is kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_STORAGE_DIR();

    /// <summary>
    /// Path, inside the Workspace's data directory, where its index is kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_WORKSPACE_INDEX_DIR();

    /// <summary>
    /// Path, inside the Vault's root, where its store is kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_STORAGE_DIR();

    /// <summary>
    /// Path, inside the Vault's root, where its index is kept
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_VAULT_INDEX_DIR();

    /// <summary>
    /// The sub-vault an address names when it names none
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_ROOT_SUB_VAULT();

    /// <summary>
    /// The port a Vault's daemon listens on when its configuration names no other.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_GLOBAL_KEYS_DIR();

    /// <summary>
    /// Keys of a user scope, under the user's local data directory
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_USER_KEYS_DIR();

    /// <summary>
    /// Keys named by the environment, under [`HOME_ENV_VAR`]
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_ENV_KEYS_DIR();

    /// <summary>
    /// The variable that names the directory an environment key set lives in
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_HOME_ENV_VAR();

    /// <summary>
    /// The extension a member's public key carries
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_PUBLIC_KEY_EXTENSION();

    /// <summary>
    /// The extension an account's private key carries
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint ROLA_PRIVATE_KEY_EXTENSION();

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_account(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_accounts(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_io_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_auth_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_member(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_members(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_key_locate_rule(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_daemon_exit(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_io_error_kind(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_bincode_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_json_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_addr_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_inverse_edge(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_vcsindex_reading_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_inverse_index_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_inverse_index_reading_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_hash_list(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_inverse_index(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_inverse_index_report(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_version_number(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_vault_address(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_action_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_vault_config(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_vault_meta_config(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_vault_daemon_config(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_vault_creation_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_vault(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_creator(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_parse_vcsindex_object_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_vcsindex_writing_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_vcsindex(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_message(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_variant(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_version(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_vcsindex_object(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_variant_type(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_workspace_config(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_workspace_creation_error(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_rola_workspace(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_configure_error_reason(nint value);

    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void free_configure_error(nint value);

    /// <summary>
    /// Every member whose public key `rule` finds, highest priority first.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_member_locate(nint vault, nint rule);

    /// <summary>
    /// The member named `member_name`, if any scope the rule turns on holds its public key.
    ///
    /// Returns an owned `RolaMember *`, or `NULL` when there is nothing; release it with `free_rola_member`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_member_find(nint member_name, nint rule);

    /// <summary>
    /// Every account whose private key `rule` finds, highest priority first.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_account_locate(nint vault, nint rule);

    /// <summary>
    /// The account named `account_name`, if a local root holds its private key.
    ///
    /// Returns an owned `RolaAccount *`, or `NULL` when there is nothing; release it with `free_rola_account`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_account_find(nint account_name, nint rule);

    /// <summary>
    /// Runs the [`ActionHandshake`](crate::ActionHandshake) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_handshake(nint workspace, nint account, nint target, nint name);

    /// <summary>
    /// Runs the [`ActionSyncAll`](crate::ActionSyncAll) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: nothing; the payload is null
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_sync_all(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionSyncIndexAll`](crate::ActionSyncIndexAll) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: nothing; the payload is null
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_sync_index_all(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionListRemote`](crate::ActionListRemote) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_list_remote(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionSyncHashes`](crate::ActionSyncHashes) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: nothing; the payload is null
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_sync_hashes(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionListRemoteIndex`](crate::ActionListRemoteIndex) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_list_remote_index(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionReadRemoteIndex`](crate::ActionReadRemoteIndex) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVCSIndexObject *`, owned; release it with `free_rola_vcsindex_object`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_read_remote_index(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionFetchLayout`](crate::ActionFetchLayout) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: nothing; the payload is null
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_fetch_layout(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionRequestOwnership`](crate::ActionRequestOwnership) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_request_ownership(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionGiveupOwnership`](crate::ActionGiveupOwnership) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_giveup_ownership(nint workspace, nint account, nint target, nint input);

    /// <summary>
    /// Runs the [`ActionMoveRemotePath`](crate::ActionMoveRemotePath) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_move_remote_path(nint workspace, nint account, nint target, nint from, nint to);

    /// <summary>
    /// Runs the [`ActionCreateRemoteEntry`](crate::ActionCreateRemoteEntry) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_create_remote_entry(nint workspace, nint account, nint target, nint path, nint uuid, nint version);

    /// <summary>
    /// Runs the [`ActionSetRemoteVersion`](crate::ActionSetRemoteVersion) action, blocking until it has.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaActionError *`, owned; release it with `free_rola_action_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult do_action_set_remote_version(nint workspace, nint account, nint target, nint uuid, nint version);

    /// <summary>
    /// Entry logic for the Rorolala Daemon, driven by a Tokio multi-threaded
    ///
    /// `daemon_begin_async` is not supported for use on the FFI side; only the
    /// blocking (block-on) mode is supported.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_daemon_begin(nint cwd, nint config);

    /// <summary>
    /// The inverse index of the Vault or Workspace `dir` is inside, if it is inside one.
    ///
    /// Returns an owned `RolaInverseIndex *`, or `NULL` when there is nothing; release it with `free_rola_inverse_index`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint locate_rola_inverse_index(nint dir);

    /// <summary>
    /// Locates a [`Vault`] by searching upwards from the given directory
    ///
    /// Returns an owned `RolaVault *`, or `NULL` when there is nothing; release it with `free_rola_vault`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint locate_rola_vault(nint vault_dir);

    /// <summary>
    /// Locates the [`VCSIndex`] the given directory is inside
    ///
    /// Returns an owned `RolaVCSIndex *`, or `NULL` when there is nothing; release it with `free_rola_vcsindex`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint locate_rola_vcs_index(nint index_dir);

    /// <summary>
    /// Locates a [`Workspace`] by searching upwards from the given directory
    ///
    /// Returns an owned `RolaWorkspace *`, or `NULL` when there is nothing; release it with `free_rola_workspace`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint locate_rola_workspace(nint workspace_dir);

    /// <summary>
    /// The account's name, which is the stem of its private key file.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_account_account_name(nint self);

    /// <summary>
    /// Where the account's private key file was found.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_account_account_key_path(nint self);

    /// <summary>
    /// How many accounts the search found.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nuint rola_accounts_len(nint self);

    /// <summary>
    /// Whether the search found no accounts at all.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool is_rola_accounts_empty(nint self);

    /// <summary>
    /// The account at `index`, counting from zero.
    ///
    /// Returns an owned `RolaAccount *`, or `NULL` when there is nothing; release it with `free_rola_account`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint read_rola_accounts_by_index(nint self, nuint index);

    /// <summary>
    /// The member's name, which is the stem of its public key file.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_member_member_name(nint self);

    /// <summary>
    /// Where the member's public key file was found.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_member_member_key_path(nint self);

    /// <summary>
    /// How many members the search found.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nuint rola_members_len(nint self);

    /// <summary>
    /// Whether the search found no members at all.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool is_rola_members_empty(nint self);

    /// <summary>
    /// The member at `index`, counting from zero.
    ///
    /// Returns an owned `RolaMember *`, or `NULL` when there is nothing; release it with `free_rola_member`.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint read_rola_members_by_index(nint self, nuint index);

    /// <summary>
    /// A rule that searches every directory.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_key_locate_rule_key_locate_rule_new();

    /// <summary>
    /// Whether the filesystem-root keys are searched.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool rola_key_locate_rule_key_locate_rule_find_global(nint self);

    /// <summary>
    /// Turns the filesystem-root keys on or off.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void rola_key_locate_rule_key_locate_rule_set_find_global(nint self, [MarshalAs(UnmanagedType.U1)] bool value);

    /// <summary>
    /// Whether the keys beside the current Vault are searched.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool rola_key_locate_rule_key_locate_rule_find_local(nint self);

    /// <summary>
    /// Turns the keys beside the current Vault on or off.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void rola_key_locate_rule_key_locate_rule_set_find_local(nint self, [MarshalAs(UnmanagedType.U1)] bool value);

    /// <summary>
    /// Whether the user's local data keys are searched.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool rola_key_locate_rule_key_locate_rule_find_user(nint self);

    /// <summary>
    /// Turns the user's local data keys on or off.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void rola_key_locate_rule_key_locate_rule_set_find_user(nint self, [MarshalAs(UnmanagedType.U1)] bool value);

    /// <summary>
    /// Whether the keys named by `ROLA_HOME` are searched.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool rola_key_locate_rule_key_locate_rule_find_env(nint self);

    /// <summary>
    /// Turns the keys named by `ROLA_HOME` on or off.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void rola_key_locate_rule_key_locate_rule_set_find_env(nint self, [MarshalAs(UnmanagedType.U1)] bool value);

    /// <summary>
    /// The kind of failure this was.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RolaIoErrorKind rola_io_error_io_error_kind(nint self);

    /// <summary>
    /// What the failure said.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_io_error_io_error_message(nint self);

    /// <summary>
    /// What the failure said.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_bincode_error_bincode_error_message(nint self);

    /// <summary>
    /// What the failure said.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_json_error_json_error_message(nint self);

    /// <summary>
    /// The line it was found on.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nuint rola_json_error_json_error_line(nint self);

    /// <summary>
    /// The column it was found on.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nuint rola_json_error_json_error_column(nint self);

    /// <summary>
    /// The target that would not read as an address.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint rola_addr_error_addr_error_target(nint self);

    /// <summary>
    /// Builds the records afresh from every object the index holds, and writes them.
    ///
    /// Blocks until the rebuild is done.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaInverseIndexReport *`, owned; release it with `free_rola_inverse_index_report`
    /// - `Err`: `RolaInverseIndexError *`, owned; release it with `free_rola_inverse_index_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult rebuild_rola_inverse_index(nint self);

    /// <summary>
    /// The variants made from the content stored under `hash`.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaHashList *`, owned; release it with `free_rola_hash_list`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_store_dependents(nint self, nint hash);

    /// <summary>
    /// The versions that fix the variant named `hash`.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaHashList *`, owned; release it with `free_rola_hash_list`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_variant_dependents(nint self, nint hash);

    /// <summary>
    /// The variants based on the version named `hash`.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaHashList *`, owned; release it with `free_rola_hash_list`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_version_dependents(nint self, nint hash);

    /// <summary>
    /// The versions based on the version named `hash`.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaHashList *`, owned; release it with `free_rola_hash_list`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_child_versions(nint self, nint hash);

    /// <summary>
    /// The variants made by the creator named `hash`.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaHashList *`, owned; release it with `free_rola_hash_list`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_creator_dependents(nint self, nint hash);

    /// <summary>
    /// The variants that say what the message named `hash` says.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaHashList *`, owned; release it with `free_rola_hash_list`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_message_dependents(nint self, nint hash);

    /// <summary>
    /// The number of the version named `hash`.
    ///
    /// Blocks until the read is done. `hash` is the hex a key is written as.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVersionNumber *`, owned; release it with `free_rola_version_number`
    /// - `Err`: `RolaInverseIndexReadingError *`, owned; release it with `free_rola_inverse_index_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult get_version_number(nint self, nint hash);

    /// <summary>
    /// How many objects the index holds.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_objects(nint self);

    /// <summary>
    /// How many of them are variants.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_variants(nint self);

    /// <summary>
    /// How many are versions.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_versions(nint self);

    /// <summary>
    /// How many are creators.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_creators(nint self);

    /// <summary>
    /// How many are messages.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_messages(nint self);

    /// <summary>
    /// How many records the inverse index has.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_entries(nint self);

    /// <summary>
    /// How many dependents are noted across the records.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong inverse_index_report_dependents(nint self);

    /// <summary>
    /// The digest of what was written, as hex.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint inverse_index_report_fingerprint(nint self);

    /// <summary>
    /// The number itself.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ulong version_number_value(nint self);

    /// <summary>
    /// The link the caller wrote, as it was written.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint vault_address_read_raw(nint self);

    /// <summary>
    /// The link's host, as the ABI spells it.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint vault_address_read_addr(nint self);

    /// <summary>
    /// The link's port, as the ABI spells it.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern ushort vault_address_read_port(nint self);

    /// <summary>
    /// Creates a Vault in the specified directory
    ///
    /// Returns a result:
    /// - `Ok`: nothing; the payload is null
    /// - `Err`: `VaultCreationError *`, owned; release it with `free_vault_creation_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult create_vault(nint dir);

    /// <summary>
    /// The Variant this object is, or an error if it is not one
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVariant *`, owned; release it with `free_rola_variant`
    /// - `Err`: `RolaParseVCSIndexObjectError *`, owned; release it with `free_rola_parse_vcsindex_object_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult expect_object_is_variant(RolaVCSIndexObject self);

    /// <summary>
    /// The Version this object is, or an error if it is not one
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVersion *`, owned; release it with `free_rola_version`
    /// - `Err`: `RolaParseVCSIndexObjectError *`, owned; release it with `free_rola_parse_vcsindex_object_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult expect_object_is_version(RolaVCSIndexObject self);

    /// <summary>
    /// The Creator this object is, or an error if it is not one
    ///
    /// Returns a result:
    /// - `Ok`: `RolaCreator *`, owned; release it with `free_rola_creator`
    /// - `Err`: `RolaParseVCSIndexObjectError *`, owned; release it with `free_rola_parse_vcsindex_object_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult expect_object_is_creator(RolaVCSIndexObject self);

    /// <summary>
    /// The Message this object is, or an error if it is not one
    ///
    /// Returns a result:
    /// - `Ok`: `RolaMessage *`, owned; release it with `free_rola_message`
    /// - `Err`: `RolaParseVCSIndexObjectError *`, owned; release it with `free_rola_parse_vcsindex_object_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult expect_object_is_message(RolaVCSIndexObject self);

    /// <summary>
    /// The Variant this object is, or an error if it is not one
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVariant *`, owned; release it with `free_rola_variant`
    /// - `Err`: `RolaParseVCSIndexObjectError *`, owned; release it with `free_rola_parse_vcsindex_object_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult try_get_variant_from_object(RolaVCSIndexObject self);

    /// <summary>
    /// The Version this object is, or an error if it is not one
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVersion *`, owned; release it with `free_rola_version`
    /// - `Err`: `RolaParseVCSIndexObjectError *`, owned; release it with `free_rola_parse_vcsindex_object_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult try_get_version_from_object(RolaVCSIndexObject self);

    /// <summary>
    /// Whether this object is a Variant
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool is_object_variant(RolaVCSIndexObject self);

    /// <summary>
    /// Whether this object is a Version
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool is_object_version(RolaVCSIndexObject self);

    /// <summary>
    /// Whether this object is a Creator
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool is_object_creator(RolaVCSIndexObject self);

    /// <summary>
    /// Whether this object is a Message
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool is_object_message(RolaVCSIndexObject self);

    /// <summary>
    /// Writes `variant` into the index, answering with the key it is stored under.
    ///
    /// Blocks until the write is done, and answers with a `char *` the caller releases with
    /// `free_string`.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaVCSIndexWritingError *`, owned; release it with `free_rola_vcsindex_writing_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult write_variant_into_index(nint self, nint variant);

    /// <summary>
    /// Writes `version` into the index, answering with the key it is stored under.
    ///
    /// Blocks until the write is done, and answers with a `char *` the caller releases with
    /// `free_string`.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaVCSIndexWritingError *`, owned; release it with `free_rola_vcsindex_writing_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult write_version_into_index(nint self, nint version);

    /// <summary>
    /// Reads the Variant stored under `hash`, which is the hex a write answered with.
    ///
    /// Blocks until the read is done.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVariant *`, owned; release it with `free_rola_variant`
    /// - `Err`: `RolaVCSIndexReadingError *`, owned; release it with `free_rola_vcsindex_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult read_variant_from_index(nint self, nint hash);

    /// <summary>
    /// Reads the Version stored under `hash`, which is the hex a write answered with.
    ///
    /// Blocks until the read is done.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaVersion *`, owned; release it with `free_rola_version`
    /// - `Err`: `RolaVCSIndexReadingError *`, owned; release it with `free_rola_vcsindex_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult read_version_from_index(nint self, nint hash);

    /// <summary>
    /// Writes `creator` into the index, answering with the key it is stored under.
    ///
    /// Blocks until the write is done, and answers with a `char *` the caller releases with
    /// `free_string`.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaVCSIndexWritingError *`, owned; release it with `free_rola_vcsindex_writing_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult write_creator_into_index(nint self, nint creator);

    /// <summary>
    /// Writes `message` into the index, answering with the key it is stored under.
    ///
    /// Blocks until the write is done, and answers with a `char *` the caller releases with
    /// `free_string`.
    ///
    /// Returns a result:
    /// - `Ok`: `char *`, owned; release it with `free_string`
    /// - `Err`: `RolaVCSIndexWritingError *`, owned; release it with `free_rola_vcsindex_writing_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult write_message_into_index(nint self, nint message);

    /// <summary>
    /// Reads the Creator stored under `hash`, which is the hex a write answered with.
    ///
    /// Blocks until the read is done.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaCreator *`, owned; release it with `free_rola_creator`
    /// - `Err`: `RolaVCSIndexReadingError *`, owned; release it with `free_rola_vcsindex_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult read_creator_from_index(nint self, nint hash);

    /// <summary>
    /// Reads the Message stored under `hash`, which is the hex a write answered with.
    ///
    /// Blocks until the read is done.
    ///
    /// Returns a result:
    /// - `Ok`: `RolaMessage *`, owned; release it with `free_rola_message`
    /// - `Err`: `RolaVCSIndexReadingError *`, owned; release it with `free_rola_vcsindex_reading_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult read_message_from_index(nint self, nint hash);

    /// <summary>
    /// The kind of this variant
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RolaVariantType get_rola_variant_type(nint self);

    /// <summary>
    /// Creates a Workspace in the specified directory
    ///
    /// Returns a result:
    /// - `Ok`: nothing; the payload is null
    /// - `Err`: `WorkspaceCreationError *`, owned; release it with `free_workspace_creation_error`
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern RorolalaResult create_workspace(nint dir);

    /// <summary>
    /// Whether the Vault is locked.
    ///
    /// Answers whether the Vault's lock file is there. A Vault locked by another run and one whose lock
    /// was left behind by a run that did not finish are both answered as locked, since a lock is the
    /// file and not a claim about who is holding it.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool RolaVault_is_locking(nint vault);

    /// <summary>
    /// Locks the Vault, handing back the guard the lock is held by.
    ///
    /// Returns a pointer the caller releases with `RolaVault_drop_locking_guard`, and null when nothing
    /// was locked. The lock is held until then — a caller that keeps the pointer keeps the lock,
    /// whatever else it does.
    ///
    /// A Vault that is locked already is not waited for: nothing is handed back and it is the caller's
    /// to decide what to do about it. Whether it was locked already or its lock file could not be made
    /// is not told here; `RolaVault_is_locking` is what says which.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint RolaVault_get_locking_guard(nint vault);

    /// <summary>
    /// Releases a guard `RolaVault_get_locking_guard` handed out, unlocking the Vault.
    ///
    /// Frees the pointer and gives the lock back with it, so the Vault is unlocked by the time this
    /// returns. A null pointer is nothing to release and does nothing.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void RolaVault_drop_locking_guard(nint guard);

    /// <summary>
    /// Whether the Workspace is locked.
    ///
    /// Answers whether the Workspace's lock file is there. A Workspace locked by another run and one
    /// whose lock was left behind by a run that did not finish are both answered as locked, since a
    /// lock is the file and not a claim about who is holding it.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    [return: MarshalAs(UnmanagedType.U1)]
    internal static extern bool RolaWorkspace_is_locking(nint workspace);

    /// <summary>
    /// Locks the Workspace, handing back the guard the lock is held by.
    ///
    /// Returns a pointer the caller releases with `RolaWorkspace_drop_locking_guard`, and null when
    /// nothing was locked. The lock is held until then — a caller that keeps the pointer keeps the lock,
    /// whatever else it does.
    ///
    /// A Workspace that is locked already is not waited for: nothing is handed back and it is the
    /// caller's to decide what to do about it. Whether it was locked already or its lock file could not
    /// be made is not told here; `RolaWorkspace_is_locking` is what says which.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern nint RolaWorkspace_get_locking_guard(nint workspace);

    /// <summary>
    /// Releases a guard `RolaWorkspace_get_locking_guard` handed out, unlocking the Workspace.
    ///
    /// Frees the pointer and gives the lock back with it, so the Workspace is unlocked by the time this
    /// returns. A null pointer is nothing to release and does nothing.
    /// </summary>
    [DllImport("rorolala", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
    internal static extern void RolaWorkspace_drop_locking_guard(nint guard);

}
