[package]
name = "rorolala-vcs"
version.workspace = true
edition.workspace = true

[dependencies]
rorolala-errors.workspace = true
rorolala-storage.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-lazyffi.workspace = true
rorolala-utils-location.workspace = true
blake3.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["io-util"] }
