// Generated by `rorolala-dev-icons` from `app/desktop/icons.toml`.
//
// Do not edit: what this holds is what the manifest says, and a change made here is a change made
// nowhere — the next `./run.sh icons` would take it away again.

namespace RorolalaVCSPlugin;

/// <summary>The pictures this plugin contributes, and the key each is handed over under.</summary>
internal static partial class Icons
{
    /// <summary>The key the `lock` picture is held under.</summary>
    public const string Lock = "rorolala_vcs.lock";

    /// <summary>The key the `create` picture is held under.</summary>
    public const string Create = "rorolala_vcs.create";

    /// <summary>Every picture, by the key it is held under and its name in the set.</summary>
    public static readonly (string Key, string Name)[] Pictures =
    [
        (Lock, "lock"),
        (Create, "create"),
    ];
}
