[package]
name = "rola"
version.workspace = true
edition.workspace = true

[dependencies]
librorolala.workspace = true
rorolala-cli-setups.workspace = true
rorolala-utils-cli-theme.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-location.workspace = true
rorolala-vault.workspace = true
rorolala-workspace.workspace = true
mingling.workspace = true
rust-i18n.workspace = true
dirs.workspace = true
