// Generated by `build.rs` from the `impl Action` blocks under `src/actions`.
// Do not edit: change the action, or `tmpl/action_func.tmpl`, and this follows.

use rorolala_auth::Account;
use rorolala_protocol::ActionError;
use rorolala_workspace::Workspace;

/// Runs the [`ActionHandshake`](crate::ActionHandshake) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_handshake_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    name: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionHandshake>(workspace, account, target, name, progress).await
}

/// Runs the [`ActionHandshake`](crate::ActionHandshake) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_handshake)]
pub fn action_handshake(
    workspace: &Workspace,
    account: &Account,
    target: String,
    name: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_handshake_async(workspace, account, target, name, Progress::silent()))
}

/// Runs the [`ActionSyncAll`](crate::ActionSyncAll) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_sync_all_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<(), ActionError> {
    proc_action::<ActionSyncAll>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionSyncAll`](crate::ActionSyncAll) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_sync_all)]
pub fn action_sync_all(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<(), ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_sync_all_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionSyncIndexAll`](crate::ActionSyncIndexAll) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_sync_index_all_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<(), ActionError> {
    proc_action::<ActionSyncIndexAll>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionSyncIndexAll`](crate::ActionSyncIndexAll) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_sync_index_all)]
pub fn action_sync_index_all(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<(), ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_sync_index_all_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionListRemote`](crate::ActionListRemote) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_list_remote_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionListRemote>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionListRemote`](crate::ActionListRemote) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_list_remote)]
pub fn action_list_remote(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_list_remote_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionSyncHashes`](crate::ActionSyncHashes) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_sync_hashes_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<(), ActionError> {
    proc_action::<ActionSyncHashes>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionSyncHashes`](crate::ActionSyncHashes) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_sync_hashes)]
pub fn action_sync_hashes(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<(), ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_sync_hashes_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionListRemoteIndex`](crate::ActionListRemoteIndex) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_list_remote_index_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionListRemoteIndex>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionListRemoteIndex`](crate::ActionListRemoteIndex) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_list_remote_index)]
pub fn action_list_remote_index(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_list_remote_index_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionReadRemoteIndex`](crate::ActionReadRemoteIndex) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_read_remote_index_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<VCSIndexObject, ActionError> {
    proc_action::<ActionReadRemoteIndex>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionReadRemoteIndex`](crate::ActionReadRemoteIndex) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_read_remote_index)]
pub fn action_read_remote_index(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<VCSIndexObject, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_read_remote_index_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionFetchLayout`](crate::ActionFetchLayout) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_fetch_layout_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<(), ActionError> {
    proc_action::<ActionFetchLayout>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionFetchLayout`](crate::ActionFetchLayout) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_fetch_layout)]
pub fn action_fetch_layout(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<(), ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_fetch_layout_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionRequestOwnership`](crate::ActionRequestOwnership) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_request_ownership_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionRequestOwnership>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionRequestOwnership`](crate::ActionRequestOwnership) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_request_ownership)]
pub fn action_request_ownership(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_request_ownership_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionGiveupOwnership`](crate::ActionGiveupOwnership) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_giveup_ownership_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionGiveupOwnership>(workspace, account, target, input, progress).await
}

/// Runs the [`ActionGiveupOwnership`](crate::ActionGiveupOwnership) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_giveup_ownership)]
pub fn action_giveup_ownership(
    workspace: &Workspace,
    account: &Account,
    target: String,
    input: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_giveup_ownership_async(workspace, account, target, input, Progress::silent()))
}

/// Runs the [`ActionMoveRemotePath`](crate::ActionMoveRemotePath) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_move_remote_path_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    from: String, to: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionMoveRemotePath>(workspace, account, target, (from, to), progress).await
}

/// Runs the [`ActionMoveRemotePath`](crate::ActionMoveRemotePath) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_move_remote_path)]
pub fn action_move_remote_path(
    workspace: &Workspace,
    account: &Account,
    target: String,
    from: String, to: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_move_remote_path_async(workspace, account, target, from, to, Progress::silent()))
}

/// Runs the [`ActionCreateRemoteEntry`](crate::ActionCreateRemoteEntry) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_create_remote_entry_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    path: String, uuid: String, version: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionCreateRemoteEntry>(workspace, account, target, (path, uuid, version), progress).await
}

/// Runs the [`ActionCreateRemoteEntry`](crate::ActionCreateRemoteEntry) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_create_remote_entry)]
pub fn action_create_remote_entry(
    workspace: &Workspace,
    account: &Account,
    target: String,
    path: String, uuid: String, version: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_create_remote_entry_async(workspace, account, target, path, uuid, version, Progress::silent()))
}

/// Runs the [`ActionSetRemoteVersion`](crate::ActionSetRemoteVersion) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// `progress` is where the action says what it is doing while it does it; a run that is not
/// being watched hands [`Progress::silent`], and the action runs the same way either way.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_set_remote_version_async(
    workspace: &Workspace,
    account: &Account,
    target: String,
    uuid: String, version: String,
    progress: Progress,
) -> Result<String, ActionError> {
    proc_action::<ActionSetRemoteVersion>(workspace, account, target, (uuid, version), progress).await
}

/// Runs the [`ActionSetRemoteVersion`](crate::ActionSetRemoteVersion) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port. Nothing is said of the action's progress here: a caller outside Rust
/// has nowhere to read it, so the action is given no one to tell.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_set_remote_version)]
pub fn action_set_remote_version(
    workspace: &Workspace,
    account: &Account,
    target: String,
    uuid: String, version: String,
) -> Result<String, ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_set_remote_version_async(workspace, account, target, uuid, version, Progress::silent()))
}
