// Generated by `build.rs` from the `impl Action` blocks under `src/actions`.
// Do not edit: change the action, or `tmpl/action_func.tmpl`, and this follows.

/// Runs the [`ActionHandshake`](crate::ActionHandshake) action on the input it is handed, taken
/// from `workspace`, as `account`, against the daemon at `target`.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails.
pub async fn action_handshake_async(workspace: &rorolala_workspace::Workspace, account: &rorolala_auth::Account, target: String, input: String) -> Result<String, rorolala_protocol::ActionError> {
    proc_action::<ActionHandshake>(workspace, account, target, input).await
}

/// Runs the [`ActionHandshake`](crate::ActionHandshake) action, blocking until it has.
///
/// This is the entry point the C ABI exports; the `async` one above is what a Rust
/// caller should use instead. `workspace` is the copy the work is taken from, and the
/// account is the one the caller names, so which identity an action runs as is theirs to
/// say and not looked up behind their back, and the target is the daemon to reach, as a
/// host and a port.
///
/// # Errors
///
/// Returns [`ActionError`](rorolala_protocol::ActionError) once the action can be
/// carried out but the exchange fails, or if the runtime cannot be built.
#[rorolala_utils_lazyffi::lazyffi(export = do_action_handshake)]
pub fn action_handshake(workspace: &rorolala_workspace::Workspace, account: &rorolala_auth::Account, target: String, input: String) -> Result<String, rorolala_protocol::ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(action_handshake_async(workspace, account, target, input))
}
