// The actions themselves, one file each. Which files there are is written down by
// `build.rs`, in the `actions` module beside them, so adding an action is adding a file and
// nothing else.
//
// The path is spelled out because a module keeps its children in a directory named after
// itself: `action.rs`'s own is `src/action/`, while the action files live in `src/actions/`.
#[path = "actions/mod.rs"]
mod actions;
pub use actions::*;

use rorolala_protocol::{Action, ActionContext, ActionError, OnlyWorkspace, Socket, parse_address};
use rorolala_utils_constants::VAULT_DEFAULT_PORT;
use tokio::net::TcpStream;

use rorolala_auth::{Account, SecureStream};

use crate::wire;

/// Runs the action `A` on `input`, as `account`, against the daemon at `target`.
///
/// The input is what the caller asked for, so it belongs to the Workspace side and is
/// wrapped as the [`OnlyWorkspace`] the action takes; the account is the one the caller
/// named, so the action runs as that identity rather than as whatever was found first; and
/// `target` is the daemon to reach, as an ip and a port.
///
/// The session is established before the action runs. The account's private key proves
/// which identity the action runs as, and a public key beside it — if there is one — is
/// the identity the peer must prove in turn. An account without one accepts the peer as
/// whoever it proves itself to be, which is what lets a Workspace that knows only its own
/// key still be challenged by a Vault.
///
/// # Errors
///
/// Returns [`ActionError::Addr`] if `target` is not an ip and a port,
/// [`ActionError::Auth`] if a key cannot be read or the peer cannot be proven, and
/// [`ActionError`] once the action can be carried out but the exchange fails.
pub async fn proc_action<A>(
    account: &Account,
    target: String,
    input: A::Input,
) -> Result<A::Output, ActionError>
where
    A: Action,
{
    // Read before anything else: a target that cannot be an address is the caller's to fix,
    // and says so here rather than at the first write. An address written without a port
    // means the one a Vault listens on by default.
    let address = parse_address(&target, VAULT_DEFAULT_PORT).map_err(ActionError::Addr)?;

    let identity = account.get_key()?;
    let expected = account.peer_key()?;

    // Prove who the action runs as, and hold the peer to an identity where the account
    // says which one that must be.
    let socket: Box<dyn Socket> = Box::new(TcpStream::connect(address).await?);
    let mut channel = match &expected {
        Some(expected) => SecureStream::connect(socket, &identity, expected).await?,
        None => SecureStream::connect_unpinned(socket, &identity).await?,
    };

    // Name the action and the account we act as, and wait for the peer to say it read the
    // same request. An id the peer does not answer for never starts an action.
    wire::write_request(
        &mut channel,
        &wire::Request {
            id: A::ID,
            account: account.name(),
        },
    )
    .await?;

    if wire::read_confirmation(&mut channel).await? != wire::confirmation(A::ID) {
        return Err(ActionError::UnknownAction(A::ID));
    }

    let input = OnlyWorkspace::from(Some(input));
    let ctx = ActionContext::new_workspace_ctx(account.clone()).with_channel(channel);

    A::process(input, ctx).await
}

// The entry points for every action under `src/actions`, and the registry they are
// reached through, both generated by `build.rs` from the `impl Action` blocks themselves.
include!("action_func.rs");
include!("registry.rs");

#[cfg(test)]
mod tests {
    use std::fs;
    use std::path::{Path, PathBuf};
    use std::sync::atomic::{AtomicUsize, Ordering};

    use ed25519_dalek::SigningKey as Ed25519SigningKey;
    use ed25519_dalek::pkcs8::spki::der::pem::LineEnding;
    use ed25519_dalek::pkcs8::{EncodePrivateKey as _, EncodePublicKey as _};
    use rorolala_auth::{
        Account, KeyAlgorithm, KeyLocateRule, SecureStream, SigningKey, find_account,
    };
    use rorolala_protocol::{Action as _, ActionContext, ActionError, Socket};
    use tokio::net::TcpListener;

    use super::{ActionHandshake, build_action_registry, do_action_with, proc_action};
    use crate::wire;

    /// A directory of its own, emptied first so a rerun starts clean.
    fn scratch(label: &str) -> PathBuf {
        static NEXT: AtomicUsize = AtomicUsize::new(0);

        let dir = std::env::temp_dir().join(format!(
            "rorolala-daemon-action-{}-{label}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));

        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();

        dir
    }

    /// An identity from a fixed seed, so a test names the same key twice.
    fn signing(seed: u8) -> SigningKey {
        SigningKey::from_bytes(KeyAlgorithm::Ed25519, [seed; 32]).unwrap()
    }

    /// Writes the private key of `identity` as the account `name`, where a search finds it.
    fn enroll(keys: &Path, name: &str, identity: &Ed25519SigningKey) {
        let pem = identity.to_pkcs8_pem(LineEnding::LF).unwrap();
        fs::write(keys.join(format!("{name}.pem")), pem.as_str()).unwrap();
    }

    /// Writes the public key of `identity` as the member `name`, where a search finds it.
    fn publish(keys: &Path, name: &str, identity: &Ed25519SigningKey) {
        let pem = identity
            .verifying_key()
            .to_public_key_pem(LineEnding::LF)
            .unwrap();
        fs::write(keys.join(format!("{name}.pub")), pem).unwrap();
    }

    /// A rule that looks only at the caller's own keys, so a test sees only what it made.
    fn local_only() -> KeyLocateRule {
        KeyLocateRule {
            find_global: false,
            find_local: true,
            find_user: false,
            find_env: false,
        }
    }

    /// An id no action claims is refused rather than mistaken for a position.
    ///
    /// Ids name actions: they are the one thing a caller outside Rust holds onto, so a
    /// list that skipped some would still reach the ones it has, and an id that names
    /// nothing is an error. `u32::MAX` is the id no action is ever given.
    #[tokio::test]
    async fn an_id_no_action_names_is_an_error() {
        let registry = build_action_registry();
        let ctx = ActionContext::new_workspace_ctx(Account::default());

        let error = do_action_with(&registry, u32::MAX, ctx)
            .await
            .expect_err("an id no action names is refused");

        assert!(matches!(error, ActionError::UnknownAction(id) if id == u32::MAX));
    }

    /// A target that would not read as an address is refused before a key is read.
    #[tokio::test]
    async fn a_target_that_is_not_an_address_is_refused() {
        // The account holds no key, so if the address were checked later this would fail
        // with an auth error instead of the address one.
        let error = proc_action::<ActionHandshake>(
            &Account::default(),
            "nowhere".to_string(),
            "world".to_string(),
        )
        .await
        .unwrap_err();

        assert!(matches!(error, ActionError::Addr(_)));
    }

    /// An account whose private key cannot be read fails before anything is sent.
    #[tokio::test]
    async fn an_account_whose_key_cannot_be_read_is_refused() {
        // `Account::default()` names a key file that is not there, and the address is one
        // that would parse, so reading the key is what fails.
        let error = proc_action::<ActionHandshake>(
            &Account::default(),
            "127.0.0.1:1".to_string(),
            "world".to_string(),
        )
        .await
        .unwrap_err();

        assert!(matches!(error, ActionError::Auth(_)));
    }

    /// An account whose peer key cannot be read fails before anything is sent.
    #[tokio::test]
    async fn an_account_whose_peer_key_cannot_be_read_is_refused() {
        let keys = scratch("peer-key");
        let client = Ed25519SigningKey::from_bytes(&[2; 32]);
        // A public key beside the private one names a peer, so the account holds its
        // peer to it — until the file is gone.
        enroll(&keys, "client", &client);
        publish(&keys, "client", &Ed25519SigningKey::from_bytes(&[3; 32]));

        let account = find_account("client", std::slice::from_ref(&keys), &local_only()).unwrap();
        fs::remove_file(keys.join("client.pub")).unwrap();

        let error = proc_action::<ActionHandshake>(
            &account,
            "127.0.0.1:1".to_string(),
            "world".to_string(),
        )
        .await
        .unwrap_err();

        assert!(matches!(error, ActionError::Auth(_)));
    }

    /// A peer that confirms some other action never starts the one that was asked for.
    #[tokio::test]
    async fn a_confirmation_that_does_not_match_the_action_is_refused() {
        let keys = scratch("mismatch");
        let client = Ed25519SigningKey::from_bytes(&[4; 32]);
        enroll(&keys, "client", &client);

        let server = signing(5);
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();

        // A peer that reads the request and answers with the confirmation of another
        // action, which is what a caller must not take for a go-ahead.
        let serving = tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            let socket: Box<dyn Socket> = Box::new(stream);
            let mut channel = SecureStream::accept(socket, &server).await.unwrap();
            let request = wire::read_request(&mut channel).await.unwrap();
            wire::write_confirmation(&mut channel, request.id + 1)
                .await
                .unwrap();
        });

        let account = find_account("client", std::slice::from_ref(&keys), &local_only()).unwrap();

        let error =
            proc_action::<ActionHandshake>(&account, address.to_string(), "world".to_string())
                .await
                .unwrap_err();

        assert!(matches!(error, ActionError::UnknownAction(id) if id == ActionHandshake::ID));
        serving.await.unwrap();
    }
}
