// The actions themselves, one file each. Which files there are is written down by
// `build.rs`, in the `actions` module beside them, so adding an action is adding a file and
// nothing else.
//
// The path is spelled out because a module keeps its children in a directory named after
// itself: `action.rs`'s own is `src/action/`, while the action files live in `src/actions/`.
#[path = "actions/mod.rs"]
mod actions;
pub use actions::*;

use rorolala_protocol::{Action, ActionContext, ActionError, OnlyWorkspace, Socket, parse_address};
use rorolala_utils_constants::VAULT_DEFAULT_PORT;
use tokio::net::TcpStream;

use rorolala_auth::{Account, SecureStream};

use crate::wire;

/// Runs the action `A` on `input`, as `account`, against the daemon at `target`.
///
/// The input is what the caller asked for, so it belongs to the Workspace side and is
/// wrapped as the [`OnlyWorkspace`] the action takes; the account is the one the caller
/// named, so the action runs as that identity rather than as whatever was found first; and
/// `target` is the daemon to reach, as an ip and a port.
///
/// The session is established before the action runs. The account's private key proves
/// which identity the action runs as, and a public key beside it — if there is one — is
/// the identity the peer must prove in turn. An account without one accepts the peer as
/// whoever it proves itself to be, which is what lets a Workspace that knows only its own
/// key still be challenged by a Vault.
///
/// # Errors
///
/// Returns [`ActionError::Addr`] if `target` is not an ip and a port,
/// [`ActionError::Auth`] if a key cannot be read or the peer cannot be proven, and
/// [`ActionError`] once the action can be carried out but the exchange fails.
pub async fn proc_action<A>(
    account: &Account,
    target: String,
    input: A::Input,
) -> Result<A::Output, ActionError>
where
    A: Action,
{
    // Read before anything else: a target that cannot be an address is the caller's to fix,
    // and says so here rather than at the first write. An address written without a port
    // means the one a Vault listens on by default.
    let address = parse_address(&target, VAULT_DEFAULT_PORT).map_err(ActionError::Addr)?;

    let identity = account.get_key()?;
    let expected = account.peer_key()?;

    // Prove who the action runs as, and hold the peer to an identity where the account
    // says which one that must be.
    let socket: Box<dyn Socket> = Box::new(TcpStream::connect(address).await?);
    let mut channel = match &expected {
        Some(expected) => SecureStream::connect(socket, &identity, expected).await?,
        None => SecureStream::connect_unpinned(socket, &identity).await?,
    };

    // Name the action and the account we act as, and wait for the peer to say it read the
    // same request. An id the peer does not answer for never starts an action.
    wire::write_request(
        &mut channel,
        &wire::Request {
            id: A::ID,
            account: account.name(),
        },
    )
    .await?;

    if wire::read_confirmation(&mut channel).await? != wire::confirmation(A::ID) {
        return Err(ActionError::UnknownAction(A::ID));
    }

    let input = OnlyWorkspace::from(Some(input));
    let ctx = ActionContext::new_workspace_ctx(account.clone()).with_channel(channel);

    A::process(input, ctx).await
}

// The entry points for every action under `src/actions`, and the registry they are
// reached through, both generated by `build.rs` from the `impl Action` blocks themselves.
include!("action_func.rs");
include!("registry.rs");

#[cfg(test)]
mod tests {
    use rorolala_auth::Account;
    use rorolala_protocol::{ActionContext, ActionError};

    use super::{build_action_registry, do_action_with};

    /// An id no action claims is refused rather than mistaken for a position.
    ///
    /// Ids name actions: they are the one thing a caller outside Rust holds onto, so a
    /// list that skipped some would still reach the ones it has, and an id that names
    /// nothing is an error. `u32::MAX` is the id no action is ever given.
    #[tokio::test]
    async fn an_id_no_action_names_is_an_error() {
        let registry = build_action_registry();
        let ctx = ActionContext::new_workspace_ctx(Account::default());

        let error = do_action_with(&registry, u32::MAX, ctx)
            .await
            .expect_err("an id no action names is refused");

        assert!(matches!(error, ActionError::UnknownAction(id) if id == u32::MAX));
    }
}
