// Generated by `build.rs` from the `impl Action` blocks under `src/actions`.
// Do not edit: change the action, or `tmpl/registry.tmpl`, and this follows.

/// What running an entry yields: what the action produced, as JSON.
pub type EntryFuture = std::pin::Pin<
    std::boxed::Box<
        dyn std::future::Future<Output = Result<String, rorolala_protocol::ActionError>> + Send,
    >,
>;

/// One action as the registry holds it: erased over the types it runs on and yields.
///
/// `Action` cannot be what the registry stores — its `Input` and `Output` differ per
/// action, and `process` takes no `self` — so this is what each entry wraps: a way to run
/// an action that names none of its types. Which id it answers to is its place in
/// [`build_action_registry`], not something it carries.
pub trait ActionEntry: Send + Sync {
    /// Runs the action against `ctx` and hands back what it produced, as JSON.
    fn run(&self, ctx: rorolala_protocol::ActionContext) -> EntryFuture;
}

impl<Entry> ActionEntry for Entry
where
    Entry: rorolala_protocol::Action + Send + Sync + 'static,
    Entry::Output: Send + 'static,
{
    fn run(&self, ctx: rorolala_protocol::ActionContext) -> EntryFuture {
        std::boxed::Box::pin(async move {
            // Nothing is handed in: what an action runs on belongs to whoever asked for
            // it, and on this side that value is still to cross.
            let output = Entry::process(rorolala_protocol::OnlyWorkspace::empty(), ctx).await?;

            serde_json::to_string(&output)
                .map_err(|error| rorolala_protocol::ActionError::Json(error.into()))
        })
    }
}

/// Every action the daemon can run, laid out by id.
///
/// The slot at index `id` is the action that answers to it, and a slot no action claims is
/// `None`: an id is a name a caller holds onto, so one that a retired action leaves behind
/// stays a hole rather than shifting the actions after it. The list is written out by
/// `build.rs` in the same pass that reads the ids, so a slot and the action in it cannot
/// disagree, and two actions claiming one id stop the build rather than one of them
/// becoming unreachable.
#[must_use]
pub fn build_action_registry() -> Vec<std::option::Option<std::boxed::Box<dyn ActionEntry>>> {
    vec![
        std::option::Option::Some(std::boxed::Box::new(ActionHandshake),)
    ]
}

/// Runs the action `id` names against `ctx`, within `registry`, and hands back what it
/// produced as JSON.
///
/// The registry is handed in rather than built here: a daemon serves for as long as it
/// runs, so the list is built once and kept, and whoever keeps it is what makes it the
/// same list for every call.
///
/// # Errors
///
/// Returns [`ActionError::UnknownAction`](rorolala_protocol::ActionError::UnknownAction)
/// when `id` names no action — a hole, or a slot past the end — and whatever the action
/// itself fails with.
pub async fn do_action_with(
    registry: &[std::option::Option<std::boxed::Box<dyn ActionEntry>>],
    id: u32,
    ctx: rorolala_protocol::ActionContext,
) -> Result<String, rorolala_protocol::ActionError> {
    let entry = registry
        .get(usize::try_from(id).unwrap_or(usize::MAX))
        .and_then(std::option::Option::as_ref)
        .ok_or(rorolala_protocol::ActionError::UnknownAction(id))?;

    entry.run(ctx).await
}

/// Runs the action `id` names, blocking until it has.
///
/// This is the entry point the C ABI can export. The context it runs against is the
/// daemon's own, which is not built yet — the same piece `proc_action` is missing.
///
/// # Errors
///
/// Returns what [`do_action_with`] does, or [`ActionError::Io`](rorolala_protocol::ActionError::Io)
/// if the runtime cannot be built.
///
/// # Panics
///
/// Panics when the daemon's context is asked for: there is none yet.
// The daemon's context is the one piece still missing, so the call after its `todo!()` is
// unreachable until the daemon's session is wired up.
#[allow(unreachable_code)]
pub fn do_action(
    registry: &[std::option::Option<std::boxed::Box<dyn ActionEntry>>],
    id: u32,
) -> Result<String, rorolala_protocol::ActionError> {
    let runtime = tokio::runtime::Runtime::new()?;
    runtime.block_on(do_action_with(registry, id, todo!("the daemon's context")))
}
