// Generated by `build.rs` from the `impl Action` blocks under `src/actions`.
// Do not edit: change the action, or `tmpl/registry.tmpl`, and this follows.

/// What running an entry yields: what the action produced, as JSON.
///
/// It borrows for as long as the context it runs against does, since the context is what
/// carries the local things the action was handed.
pub type EntryFuture<'a> = std::pin::Pin<
    std::boxed::Box<
        dyn std::future::Future<Output = Result<String, rorolala_protocol::ActionError>>
            + Send
            + 'a,
    >,
>;

/// One action as the registry holds it: erased over the types it runs on and yields.
///
/// `Action` cannot be what the registry stores — its `Input` and `Output` differ per
/// action, and `process` takes no `self` — so this is what each entry wraps: a way to run
/// an action that names none of its types. Which id it answers to is its place in
/// [`build_action_registry`], not something it carries.
pub trait ActionEntry: Send + Sync {
    /// Runs the action against `ctx` and hands back what it produced, as JSON.
    fn run<'a>(&self, ctx: rorolala_protocol::ActionContext<'a>) -> EntryFuture<'a>;
}

impl<Entry> ActionEntry for Entry
where
    Entry: rorolala_protocol::Action + Send + Sync + 'static,
    Entry::Output: Send + 'static,
{
    fn run<'a>(&self, ctx: rorolala_protocol::ActionContext<'a>) -> EntryFuture<'a> {
        std::boxed::Box::pin(async move {
            // Nothing is handed in: what an action runs on belongs to whoever asked for
            // it, and on this side that value is still to cross.
            let output = Entry::process(rorolala_protocol::OnlyWorkspace::empty(), ctx).await?;

            serde_json::to_string(&output)
                .map_err(|error| rorolala_protocol::ActionError::Json(error.into()))
        })
    }
}

/// Every action the daemon can run, laid out by id.
///
/// The slot at index `id` is the action that answers to it, and a slot no action claims is
/// `None`: an id is a name a caller holds onto, so one that a retired action leaves behind
/// stays a hole rather than shifting the actions after it. The list is written out by
/// `build.rs` in the same pass that reads the ids, so a slot and the action in it cannot
/// disagree, and two actions claiming one id stop the build rather than one of them
/// becoming unreachable.
#[must_use]
pub fn build_action_registry() -> Vec<std::option::Option<std::boxed::Box<dyn ActionEntry>>> {
    vec![
        std::option::Option::Some(std::boxed::Box::new(ActionHandshake)),
    ]
}

/// Runs the action `id` names against `ctx`, within `registry`, and hands back what it
/// produced as JSON.
///
/// The registry is handed in rather than built here: a daemon serves for as long as it
/// runs, so the list is built once and kept, and whoever keeps it is what makes it the
/// same list for every call.
///
/// # Errors
///
/// Returns [`ActionError::UnknownAction`](rorolala_protocol::ActionError::UnknownAction)
/// when `id` names no action — a hole, or a slot past the end — and whatever the action
/// itself fails with.
pub async fn do_action_with(
    registry: &[std::option::Option<std::boxed::Box<dyn ActionEntry>>],
    id: u32,
    ctx: rorolala_protocol::ActionContext<'_>,
) -> Result<String, rorolala_protocol::ActionError> {
    let entry = registry
        .get(usize::try_from(id).unwrap_or(usize::MAX))
        .and_then(std::option::Option::as_ref)
        .ok_or(rorolala_protocol::ActionError::UnknownAction(id))?;

    entry.run(ctx).await
}
