[package]
name = "rorolala-workspace"
version.workspace = true
edition.workspace = true

[dependencies]
rorolala-errors.workspace = true
rorolala-storage.workspace = true
rorolala-utils-configure.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-lazyffi.workspace = true
rorolala-utils-location.workspace = true
serde.workspace = true

[dev-dependencies]
toml.workspace = true
