//! Generates the C# bindings for Rorolala's C ABI, from the C header `rorolala-dev-bindgen` writes.
//!
//! The input is the header, not the Rust sources: what a C# caller may name is exactly what the
//! header declares, so reading it is what keeps the two surfaces the same one. A C# project
//! (`RolaSharp`) runs this on every build, so its bindings are never stale against the header.
//!
//! # What is generated
//!
//! A free function becomes a `[DllImport]` extern on `RolaSharp.RorolalaBinding`, a named enum
//! becomes a C# enum, and a complete struct or union becomes a `[StructLayout]` struct — a union an
//! explicit layout. Every pointer becomes a `nint`, because the header cannot say what a pointer
//! points at and the layer above owns the marshalling: a returned string is a pointer to release
//! with `free_string`. Every member is `internal`, so the assembly's public shape is empty and the
//! hand-written, more OOP layer is what a caller sees.
//!
//! A name the header only forward-declares is not emitted — it can only cross as a pointer, and
//! every pointer is a `nint`. A type held **by value** is looked up in the header, and an opaque one
//! there is refused, since C could not lay it out either.

#![doc = include_str!("../README.md")]
#![deny(missing_docs)]
#![deny(warnings)]
#![deny(rust_2018_idioms)]
#![deny(clippy::pedantic)]
#![deny(clippy::nursery)]

use std::collections::BTreeSet;
use std::error::Error as StdError;
use std::fmt::{self, Write as _};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

/// The native library every binding is imported from.
///
/// The bare name is resolved by the platform's own rules — `librorolala.so`, `rorolala.dll` — which
/// is what an export lays beside a consumer.
const LIBRARY: &str = "rorolala";

/// The banner and the file-level directives every generated file opens with.
const BANNER: &str = "\
// <auto-generated />
//
// The C ABI of `librorolala`, bound from `rorolala_ffi.h` by `rorolala-dev-rsharp-bindgen`. DO NOT
// EDIT — the build rewrites this file, and an edit is lost with it.
//
// Every member is internal: this is the boilerplate half of the library, and the more OOP layer a
// caller is meant to use is hand-written over it. What crosses is raw — every pointer is a `nint`,
// and a string comes back as a pointer to release with `free_string` — so that layer owns the
// marshalling.

#nullable disable
#pragma warning disable

using System.Runtime.InteropServices;

namespace RolaSharp;

";

/// C# keywords, which a C name may collide with and which are then escaped.
const KEYWORDS: &[&str] = &[
    "abstract",
    "as",
    "base",
    "bool",
    "break",
    "byte",
    "case",
    "catch",
    "char",
    "checked",
    "class",
    "const",
    "continue",
    "decimal",
    "default",
    "delegate",
    "do",
    "double",
    "else",
    "enum",
    "event",
    "explicit",
    "extern",
    "false",
    "finally",
    "fixed",
    "float",
    "for",
    "foreach",
    "goto",
    "if",
    "implicit",
    "in",
    "int",
    "interface",
    "internal",
    "is",
    "lock",
    "long",
    "namespace",
    "new",
    "null",
    "object",
    "operator",
    "out",
    "override",
    "params",
    "private",
    "protected",
    "public",
    "readonly",
    "ref",
    "return",
    "sbyte",
    "sealed",
    "short",
    "sizeof",
    "stackalloc",
    "static",
    "string",
    "struct",
    "switch",
    "this",
    "throw",
    "true",
    "try",
    "typeof",
    "uint",
    "ulong",
    "unchecked",
    "unsafe",
    "ushort",
    "using",
    "virtual",
    "void",
    "volatile",
    "while",
];

/// What one generation run needs.
#[derive(Debug)]
pub struct Config<'paths> {
    /// The header to read.
    pub header: &'paths Path,
    /// The C# file to write; its directory is created when missing.
    pub binding: &'paths Path,
}

/// What can go wrong while generating the bindings.
#[derive(Debug)]
pub enum Error {
    /// A file could not be read or written.
    Io {
        /// The offending path.
        path: PathBuf,
        /// The underlying error.
        source: io::Error,
    },
    /// The header is not shaped the way this generator reads.
    Shape {
        /// What is wrong with it.
        reason: String,
    },
}

impl fmt::Display for Error {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(formatter, "{}: {source}", path.display()),
            Self::Shape { reason } => formatter.write_str(reason),
        }
    }
}

impl StdError for Error {
    fn source(&self) -> Option<&(dyn StdError + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Shape { .. } => None,
        }
    }
}

/// Generates the C# bindings and returns the path they were written to.
///
/// # Errors
///
/// Fails when the header cannot be read or the binding written, or when the header holds a
/// declaration this generator does not read — an item that is not an enum, struct, union or
/// function, or a type named by value that the header does not complete.
pub fn generate(config: &Config<'_>) -> Result<PathBuf, Error> {
    let source = fs::read_to_string(config.header).map_err(|error| Error::Io {
        path: config.header.to_path_buf(),
        source: error,
    })?;

    let csharp = render(&parse(&source)?)?;

    if let Some(parent) = config.binding.parent() {
        fs::create_dir_all(parent).map_err(|error| Error::Io {
            path: parent.to_path_buf(),
            source: error,
        })?;
    }

    fs::write(config.binding, csharp).map_err(|error| Error::Io {
        path: config.binding.to_path_buf(),
        source: error,
    })?;

    Ok(config.binding.to_path_buf())
}

/// A reason the header is not read, as an error.
fn shape(reason: &str) -> Error {
    Error::Shape {
        reason: reason.to_string(),
    }
}

/// One declaration of the surface.
#[derive(Debug)]
enum Item {
    /// A named type.
    Type(Decl),
    /// A function.
    Function(Function),
}

/// A named type declared by the header.
#[derive(Debug)]
struct Decl {
    /// What the declaration is documented with, or empty.
    doc: String,
    /// The C name.
    name: String,
    /// What kind of type it is.
    kind: Kind,
    /// Whether the header only forward-declares it.
    opaque: bool,
    /// Its members, for a complete enum, struct or union.
    members: Vec<Member>,
}

/// What a named type is.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Kind {
    /// An enumeration.
    Enum,
    /// A structure.
    Struct,
    /// A union.
    Union,
}

/// One member of a type.
#[derive(Debug)]
enum Member {
    /// One value of an enumeration.
    Variant {
        /// What it is documented with, or empty.
        doc: String,
        /// The C name.
        name: String,
        /// The value it is stated as.
        value: String,
    },
    /// One field of a struct or union.
    Field {
        /// What it is documented with, or empty.
        doc: String,
        /// The C name.
        name: String,
        /// Its type.
        ty: CType,
    },
}

/// A function declared by the header.
#[derive(Debug)]
struct Function {
    /// What it is documented with, or empty.
    doc: String,
    /// The C name.
    name: String,
    /// What it returns.
    ret: CType,
    /// Its parameters, in order.
    params: Vec<(CType, String)>,
}

/// A type as the header spells it, as far as C# needs to know.
#[derive(Debug, Clone)]
enum CType {
    /// `void`.
    Void,
    /// `bool`, which crosses as one byte.
    Bool,
    /// One of the fixed-width scalars, named by its C# spelling.
    Scalar(&'static str),
    /// A named type, held by value.
    Named(String),
    /// Anything with a `*`, which C# spells `nint`.
    Pointer,
}

/// A token of the header.
#[derive(Debug, Clone, PartialEq, Eq)]
enum Token {
    /// An identifier.
    Ident(String),
    /// A run of digits.
    Number(String),
    /// A comment, cleaned of its marks.
    Doc(String),
    /// `*`.
    Star,
    /// `{`.
    OpenBrace,
    /// `}`.
    CloseBrace,
    /// `(`.
    OpenParen,
    /// `)`.
    CloseParen,
    /// `;`.
    Semi,
    /// `,`.
    Comma,
    /// `=`.
    Assign,
}

/// Reads the header into the items it declares.
fn parse(source: &str) -> Result<Vec<Item>, Error> {
    let tokens = tokenize(body(source))?;
    let mut at = 0usize;
    let mut doc = String::new();
    let mut items = Vec::new();

    while let Some(token) = tokens.get(at) {
        match token {
            Token::Doc(text) => {
                doc.clone_from(text);
                at += 1;
            }
            Token::Ident(word) if word == "typedef" => {
                items.push(Item::Type(parse_typedef(&tokens, &mut at, &mut doc)?));
            }
            Token::Ident(_) => {
                items.push(Item::Function(parse_function(&tokens, &mut at, &mut doc)?));
            }
            _ => at += 1,
        }
    }

    Ok(items)
}

/// The declarations of the header, with the preamble and footer trimmed.
fn body(source: &str) -> &str {
    let start = source
        .find("extern \"C\" {")
        .map_or(0, |at| at + "extern \"C\" {".len());
    let end = source.rfind("#ifdef __cplusplus").unwrap_or(source.len());

    source.get(start..end).unwrap_or(source)
}

/// Reads one `typedef`.
fn parse_typedef(tokens: &[Token], at: &mut usize, doc: &mut String) -> Result<Decl, Error> {
    *at += 1;
    let kind = match expect_ident(tokens, at)?.as_str() {
        "enum" => Kind::Enum,
        "struct" => Kind::Struct,
        "union" => Kind::Union,
        other => return Err(shape(&format!("`typedef {other}` is not a type"))),
    };

    let name = expect_ident(tokens, at)?;
    let doc = std::mem::take(doc);

    let (opaque, members) = if matches!(tokens.get(*at), Some(Token::OpenBrace)) {
        *at += 1;
        let members = parse_members(tokens, at, kind)?;
        expect(tokens, at, &Token::CloseBrace, "`}`")?;
        (false, members)
    } else {
        (true, Vec::new())
    };

    // The alias names the same type as the tag, which is how every declaration in the header is
    // written; it is read and dropped, since C# names one type once.
    let _alias = expect_ident(tokens, at)?;
    expect(tokens, at, &Token::Semi, "`;`")?;

    Ok(Decl {
        doc,
        name,
        kind,
        opaque,
        members,
    })
}

/// Reads the members between a type's braces.
fn parse_members(tokens: &[Token], at: &mut usize, kind: Kind) -> Result<Vec<Member>, Error> {
    let mut members = Vec::new();
    let mut doc = String::new();

    loop {
        match tokens.get(*at) {
            None | Some(Token::CloseBrace) => break,
            Some(Token::Doc(text)) => {
                doc.clone_from(text);
                *at += 1;
            }
            Some(_) if kind == Kind::Enum => {
                let name = expect_ident(tokens, at)?;
                expect(tokens, at, &Token::Assign, "`=`")?;
                let value = expect_number(tokens, at)?;

                if matches!(tokens.get(*at), Some(Token::Comma)) {
                    *at += 1;
                }

                members.push(Member::Variant {
                    doc: std::mem::take(&mut doc),
                    name,
                    value,
                });
            }
            Some(_) => {
                let mut slice = Vec::new();

                while let Some(token) = tokens.get(*at) {
                    if matches!(token, Token::Semi) {
                        break;
                    }

                    if !matches!(token, Token::Doc(_)) {
                        slice.push(token.clone());
                    }

                    *at += 1;
                }

                expect(tokens, at, &Token::Semi, "`;`")?;
                let (ty, name) = split_declaration(&slice)?;
                members.push(Member::Field {
                    doc: std::mem::take(&mut doc),
                    name,
                    ty,
                });
            }
        }
    }

    Ok(members)
}

/// Reads one function declaration.
fn parse_function(tokens: &[Token], at: &mut usize, doc: &mut String) -> Result<Function, Error> {
    let mut head = Vec::new();

    while let Some(token) = tokens.get(*at) {
        if matches!(token, Token::OpenParen) {
            break;
        }

        head.push(token.clone());
        *at += 1;
    }

    expect(tokens, at, &Token::OpenParen, "`(`")?;

    // The name is the last identifier before the `(`; what precedes it is the return type.
    let name_at = head
        .iter()
        .rposition(|token| matches!(token, Token::Ident(_)))
        .ok_or_else(|| shape("a declaration names no function"))?;

    let name = match head.get(name_at) {
        Some(Token::Ident(word)) => word.clone(),
        _ => return Err(shape("a declaration names no function")),
    };

    head.truncate(name_at);
    let ret = ctype_from(&head)?;

    let mut params = Vec::new();
    let mut slice = Vec::new();

    while let Some(token) = tokens.get(*at) {
        match token {
            Token::CloseParen => break,
            Token::Comma => {
                if let Some(parameter) = split_parameter(&slice)? {
                    params.push(parameter);
                }

                slice.clear();
                *at += 1;
            }
            _ => {
                slice.push(token.clone());
                *at += 1;
            }
        }
    }

    if let Some(parameter) = split_parameter(&slice)? {
        params.push(parameter);
    }

    expect(tokens, at, &Token::CloseParen, "`)`")?;
    expect(tokens, at, &Token::Semi, "`;`")?;

    Ok(Function {
        doc: std::mem::take(doc),
        name,
        ret,
        params,
    })
}

/// Reads one parameter, or nothing when the list is the `void` that names no parameters.
fn split_parameter(tokens: &[Token]) -> Result<Option<(CType, String)>, Error> {
    if matches!(tokens, [Token::Ident(word)] if word == "void") {
        return Ok(None);
    }

    Ok(Some(split_declaration(tokens)?))
}

/// Reads a declaration written `<type> <name>`, as a parameter or a field is.
fn split_declaration(tokens: &[Token]) -> Result<(CType, String), Error> {
    let name_at = tokens
        .iter()
        .rposition(|token| matches!(token, Token::Ident(_)))
        .ok_or_else(|| shape("a declaration names nothing"))?;

    let name = match tokens.get(name_at) {
        Some(Token::Ident(word)) => word.clone(),
        _ => return Err(shape("a declaration names nothing")),
    };

    let head = tokens.get(..name_at).unwrap_or_default();

    Ok((ctype_from(head)?, name))
}

/// Reads a type, as far as C# needs to know it.
fn ctype_from(tokens: &[Token]) -> Result<CType, Error> {
    if tokens.iter().any(|token| matches!(token, Token::Star)) {
        return Ok(CType::Pointer);
    }

    let words: Vec<&str> = tokens
        .iter()
        .filter_map(|token| match token {
            Token::Ident(word) if word != "const" => Some(word.as_str()),
            _ => None,
        })
        .collect();

    let [word] = words.as_slice() else {
        return Err(shape("a type is not a single name"));
    };

    Ok(classify(word))
}

/// A C type name as C# spells it.
fn classify(name: &str) -> CType {
    match name {
        "void" => CType::Void,
        "bool" => CType::Bool,
        "int8_t" => CType::Scalar("sbyte"),
        "uint8_t" | "char" => CType::Scalar("byte"),
        "int16_t" => CType::Scalar("short"),
        "uint16_t" => CType::Scalar("ushort"),
        "int32_t" => CType::Scalar("int"),
        "uint32_t" => CType::Scalar("uint"),
        "int64_t" => CType::Scalar("long"),
        "uint64_t" => CType::Scalar("ulong"),
        "intptr_t" | "ptrdiff_t" | "ssize_t" => CType::Scalar("nint"),
        "uintptr_t" | "size_t" => CType::Scalar("nuint"),
        "float" => CType::Scalar("float"),
        "double" => CType::Scalar("double"),
        other => CType::Named(other.to_string()),
    }
}

/// Reads the header, in the one style the generator writes it in.
fn tokenize(source: &str) -> Result<Vec<Token>, Error> {
    let bytes = source.as_bytes();
    let mut tokens = Vec::new();
    let mut at = 0usize;

    while at < bytes.len() {
        let byte = bytes[at];

        if byte == b'#' {
            while at < bytes.len() && bytes[at] != b'\n' {
                at += 1;
            }

            continue;
        }

        if byte == b'/' && bytes.get(at + 1) == Some(&b'*') {
            let start = at;
            at += 2;

            while at + 1 < bytes.len() && !(bytes[at] == b'*' && bytes[at + 1] == b'/') {
                at += 1;
            }

            if at + 1 >= bytes.len() {
                return Err(shape("a comment is not closed"));
            }

            at += 2;
            let raw = source.get(start..at).unwrap_or_default();

            // The banner is a comment like any other, but it documents the file rather than what
            // follows it, so it is dropped rather than attached to the first declaration.
            if !raw.starts_with("/*!") {
                tokens.push(Token::Doc(clean_doc(raw)));
            }

            continue;
        }

        if let Some(token) = punctuation(byte) {
            tokens.push(token);
            at += 1;

            continue;
        }

        if byte.is_ascii_alphabetic() || byte == b'_' {
            let start = at;
            at += 1;

            while at < bytes.len() && (bytes[at].is_ascii_alphanumeric() || bytes[at] == b'_') {
                at += 1;
            }

            tokens.push(Token::Ident(
                source.get(start..at).unwrap_or_default().to_string(),
            ));

            continue;
        }

        if byte.is_ascii_digit() {
            let start = at;
            at += 1;

            while at < bytes.len() && bytes[at].is_ascii_digit() {
                at += 1;
            }

            tokens.push(Token::Number(
                source.get(start..at).unwrap_or_default().to_string(),
            ));

            continue;
        }

        at += 1;
    }

    Ok(tokens)
}

/// The token a single punctuation byte stands for, or nothing when it is none.
const fn punctuation(byte: u8) -> Option<Token> {
    Some(match byte {
        b'*' => Token::Star,
        b'{' => Token::OpenBrace,
        b'}' => Token::CloseBrace,
        b'(' => Token::OpenParen,
        b')' => Token::CloseParen,
        b';' => Token::Semi,
        b',' => Token::Comma,
        b'=' => Token::Assign,
        _ => return None,
    })
}

/// A comment's text, without its marks and the star each line carries.
fn clean_doc(raw: &str) -> String {
    let inner = raw.strip_prefix("/*").unwrap_or(raw);
    let inner = inner.strip_suffix("*/").unwrap_or(inner);

    let mut lines: Vec<&str> = inner
        .lines()
        .map(|line| {
            let text = line.trim();
            text.strip_prefix('*').map_or(text, str::trim_start)
        })
        .collect();

    while lines.first().is_some_and(|line| line.is_empty()) {
        lines.remove(0);
    }

    while lines.last().is_some_and(|line| line.is_empty()) {
        lines.pop();
    }

    lines.join("\n")
}

/// Reads one identifier, or fails.
fn expect_ident(tokens: &[Token], at: &mut usize) -> Result<String, Error> {
    match tokens.get(*at) {
        Some(Token::Ident(word)) => {
            *at += 1;
            Ok(word.clone())
        }
        _ => Err(shape("expected a name")),
    }
}

/// Reads one number, or fails.
fn expect_number(tokens: &[Token], at: &mut usize) -> Result<String, Error> {
    match tokens.get(*at) {
        Some(Token::Number(value)) => {
            *at += 1;
            Ok(value.clone())
        }
        _ => Err(shape("expected a number")),
    }
}

/// Reads one token that must be `wanted`, or fails.
fn expect(tokens: &[Token], at: &mut usize, wanted: &Token, what: &str) -> Result<(), Error> {
    if tokens.get(*at) == Some(wanted) {
        *at += 1;
        Ok(())
    } else {
        Err(shape(&format!("expected {what}")))
    }
}

/// Renders the whole surface as one C# file.
fn render(items: &[Item]) -> Result<String, Error> {
    check(items)?;

    let mut out = String::new();
    out.push_str(BANNER);

    for item in items {
        // A type the header only forward-declares is not emitted: it can only cross as a pointer, and
        // every pointer is a `nint`.
        if let Item::Type(decl) = item
            && !decl.opaque
        {
            render_decl(&mut out, decl);
        }
    }

    let _ = writeln!(out, "internal static partial class RorolalaBinding\n{{");

    for item in items {
        if let Item::Function(function) = item {
            render_function(&mut out, function);
        }
    }

    let _ = writeln!(out, "}}");

    Ok(out)
}

/// Refuses a type held by value that the header only forward-declares: C could not lay it out
/// either, so a C# struct would be a layout the two sides disagree about.
fn check(items: &[Item]) -> Result<(), Error> {
    let opaque: BTreeSet<&str> = items
        .iter()
        .filter_map(|item| match item {
            Item::Type(decl) if decl.opaque => Some(decl.name.as_str()),
            _ => None,
        })
        .collect();

    for item in items {
        match item {
            Item::Type(decl) => {
                for member in &decl.members {
                    if let Member::Field { ty, name, .. } = member {
                        held_by_value(ty, name, &opaque)?;
                    }
                }
            }
            Item::Function(function) => {
                held_by_value(&function.ret, &function.name, &opaque)?;

                for (ty, name) in &function.params {
                    held_by_value(ty, name, &opaque)?;
                }
            }
        }
    }

    Ok(())
}

/// Refuses one type held by value when the header leaves it opaque.
fn held_by_value(ty: &CType, at: &str, opaque: &BTreeSet<&str>) -> Result<(), Error> {
    if let CType::Named(name) = ty
        && opaque.contains(name.as_str())
    {
        return Err(shape(&format!(
            "`{at}` names the opaque type `{name}` by value"
        )));
    }

    Ok(())
}

/// Renders one named type.
fn render_decl(out: &mut String, decl: &Decl) {
    push_doc(out, &decl.doc, "");

    match decl.kind {
        Kind::Enum => render_enum(out, decl),
        Kind::Struct | Kind::Union => render_record(out, decl),
    }
}

/// Renders an enumeration.
fn render_enum(out: &mut String, decl: &Decl) {
    let _ = writeln!(out, "internal enum {} : int\n{{", decl.name);

    for member in &decl.members {
        if let Member::Variant { doc, name, value } = member {
            push_doc(out, doc, "    ");
            let _ = writeln!(out, "    {} = {value},", escape(name));
        }
    }

    let _ = writeln!(out, "}}\n");
}

/// Renders a struct or a union, the latter as an explicit layout.
fn render_record(out: &mut String, decl: &Decl) {
    let layout = if decl.kind == Kind::Union {
        "Explicit"
    } else {
        "Sequential"
    };

    let _ = writeln!(out, "[StructLayout(LayoutKind.{layout})]");
    let _ = writeln!(out, "internal struct {}\n{{", decl.name);

    for member in &decl.members {
        if let Member::Field { doc, name, ty } = member {
            push_doc(out, doc, "    ");

            if decl.kind == Kind::Union {
                let _ = writeln!(out, "    [FieldOffset(0)]");
            }

            let _ = writeln!(out, "    public {};", declaration(ty, name));
        }
    }

    let _ = writeln!(out, "}}\n");
}

/// Renders one function as a `[DllImport]` extern.
fn render_function(out: &mut String, function: &Function) {
    push_doc(out, &function.doc, "    ");

    let params: Vec<String> = function
        .params
        .iter()
        .map(|(ty, name)| declaration(ty, name))
        .collect();

    let _ = writeln!(
        out,
        "    [DllImport(\"{LIBRARY}\", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]"
    );

    // A return attribute is written above the method, with the others: it may not sit between the
    // modifiers and the return type.
    if matches!(function.ret, CType::Bool) {
        let _ = writeln!(out, "    [return: MarshalAs(UnmanagedType.U1)]");
    }

    let _ = writeln!(
        out,
        "    internal static extern {} {}({});\n",
        name_of(&function.ret),
        function.name,
        params.join(", ")
    );
}

/// A type as it is written before a name, with the marshalling a `bool` needs.
fn declaration(ty: &CType, name: &str) -> String {
    let mut out = String::new();

    if matches!(ty, CType::Bool) {
        out.push_str("[MarshalAs(UnmanagedType.U1)] ");
    }

    out.push_str(name_of(ty));
    out.push(' ');
    out.push_str(&escape(name));

    out
}

/// The C# spelling of a type.
fn name_of(ty: &CType) -> &str {
    match ty {
        CType::Void => "void",
        CType::Bool => "bool",
        CType::Scalar(name) => name,
        CType::Named(name) => name,
        CType::Pointer => "nint",
    }
}

/// Writes a declaration's documentation as an XML doc comment.
fn push_doc(out: &mut String, doc: &str, indent: &str) {
    if doc.is_empty() {
        return;
    }

    let _ = writeln!(out, "{indent}/// <summary>");

    for line in doc.lines() {
        let escaped = xml_escape(line);

        if escaped.is_empty() {
            let _ = writeln!(out, "{indent}///");
        } else {
            let _ = writeln!(out, "{indent}/// {escaped}");
        }
    }

    let _ = writeln!(out, "{indent}/// </summary>");
}

/// XML-escapes a line, so documentation that mentions a `<` or an `&` still compiles.
fn xml_escape(text: &str) -> String {
    text.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
}

/// A C name as a C# identifier, escaped where it collides with a keyword.
fn escape(name: &str) -> String {
    if KEYWORDS.contains(&name) {
        format!("@{name}")
    } else {
        name.to_string()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = "\
/*!
 * This file is automatically generated.
 */
#ifndef ROROLALA_FFI_H
#define ROROLALA_FFI_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern \"C\" {
#endif

void free_string(char *string);

/** Which side of a result a value is. */
typedef enum RorolalaResultTag {
  /** The call succeeded. */
  RorolalaResult_Ok = 0,
  /** The call failed. */
  RorolalaResult_Err = 1,
} RorolalaResultTag;

/**
 * What a fallible export hands back.
 */
typedef struct RorolalaResult {
  RorolalaResultTag tag;
  void * payload;
} RorolalaResult;

/** A thing the header leaves opaque. */
typedef struct RolaThing RolaThing;

void free_rola_thing(RolaThing *value);

/** Reads a name. */
char *read_name(const RolaThing * self, bool loud, uintptr_t index);

#ifdef __cplusplus
}
#endif

#endif  /* ROROLALA_FFI_H */
";

    #[test]
    fn renders_a_small_surface() {
        let items = parse(SAMPLE).unwrap_or_else(|error| panic!("{error}"));
        let csharp = render(&items).unwrap_or_else(|error| panic!("{error}"));

        assert!(csharp.contains("namespace RolaSharp;"));
        assert!(csharp.contains("internal static partial class RorolalaBinding"));
        assert!(csharp.contains("internal enum RorolalaResultTag : int"));
        assert!(csharp.contains("RorolalaResult_Ok = 0,"));
        assert!(csharp.contains("[StructLayout(LayoutKind.Sequential)]"));
        assert!(csharp.contains("public RorolalaResultTag tag;"));
        assert!(csharp.contains("public nint payload;"));
        assert!(csharp.contains("internal static extern void free_string(nint @string);"));
        assert!(csharp.contains(
            "internal static extern nint read_name(nint self, [MarshalAs(UnmanagedType.U1)] bool loud, nuint index);"
        ));
        assert!(csharp.contains("/// <summary>"));
    }

    #[test]
    fn refuses_an_opaque_type_held_by_value() {
        let source = SAMPLE.replace("const RolaThing * self", "RolaThing self");
        let items = parse(&source).unwrap_or_else(|error| panic!("{error}"));

        assert!(render(&items).is_err());
    }
}
