[package]
name = "rorolala-vault"
version.workspace = true
edition.workspace = true

[dependencies]
rorolala-storage.workspace = true
rorolala-utils-configure.workspace = true
rorolala-utils-constants.workspace = true
rorolala-utils-lazyffi.workspace = true
rorolala-utils-location.workspace = true
just_fmt.workspace = true
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
toml.workspace = true
